### ISSUE TITLE
Fixing white Background of Home section 

### ISSUE THREAD

**Issue by dhairyagothi** [Mehtarishita/StationGuide#10]
# ✨ Feature Request

white background image of hero section 
### **Description of the Feature**

white background image of hero section 

### **Problem Statement**

![image](https://github.com/user-attachments/assets/14a1cfd0-84a5-4aec-9812-22325547a778)

fixing this

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by shreyad2806** [comment]
Please assign issue to me under Gssoc

**Comment by dhairyagothi** [comment]
Lesssss Gooooo @shreyad2806 
Make PR after making changes ,

**Comment by rishyym0927** [comment]
can you assgin this issue to me?

**Comment by dhairyagothi** [comment]
assigning @rishyym0927  make a PR asap

**Comment by anushkaa-dubey** [comment]
Please assign this issue to me, i will make  PR

**Comment by dhairyagothi** [comment]
> Please assign this issue to me, i will make PR

Assigned @anushkaa-dubey please do it fast
