### ISSUE TITLE
[Backend Issue]: Adding backend for booking

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#103]
# 🛠️ Backend Issue

### **Description**
The application does not have booking functionality . A backend route/api is needed for the purpose

### **Steps to Reproduce**
I will add bookingController/api in the backend of the project.
   
### **Are you participating in GSSoC?**
- [x ] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
please explain in more detail @haseebzaki-07

**Comment by haseebzaki-07** [comment]
so we have to set up database then create route handlers for the booking purpose that receive the booking details in json format and store in the database. @dhairyagothi

**Comment by dhairyagothi** [comment]
> so we have to set up database then create route handlers for the booking purpose that receive the booking details in json format and store in the database. @dhairyagothi

okay okay make changes and make PR
