### ISSUE TITLE
[Backend Issue]: Missing handleRegister function logic in register.jsx for form submission.

### ISSUE THREAD

**Issue by Yashhuc** [Mehtarishita/StationGuide#104]
# 🛠️ Backend Issue

### **Description**

The Register component in register.jsx contains a form for user registration, but the handleRegister function lacks the necessary logic to handle form submission and communicate with the backend. This prevents users from successfully registering, as their data is not being sent to the API.

### **Steps to Reproduce**

1. Click the "Register" button.
2. Fill in the registration form fields (Name, Phone Number, Email, and Password).
3. Observe that no action is taken, and the form data is not submitted.

 
### Proposed Solution: Implement the handleRegister function as follows:

1. Collect the user data from the form fields (stored in state).
2. Use fetch or axios to send a POST request to the backend registration endpoint (/api/register).
3. Handle the success or failure response from the backend and provide appropriate feedback to the user.

### Screenshot
![image](https://github.com/user-attachments/assets/3f1d9e2c-97b9-4c33-9ef6-2b645f1cd4f8)

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
good go for it @Yashhuc

**Comment by MohammedJunaid02** [comment]
Shall i start working on this issue? @dhairyagothi @Yashhuc

**Comment by dhairyagothi** [comment]
@Yashhuc please update

**Comment by Yashhuc** [comment]
Hey, thanks for your patience. I'm still working on it. I will give you the final update by tomorrow evening.

**Comment by Yashhuc** [comment]
Hey @dhairyagothi .
I have implemented the handle register functionality as part of the project. However, I haven't been able to test it on my local server since I don't have MongoDB experience. I have updated the fetch URL to the deployed URL instead.

![image](https://github.com/user-attachments/assets/b485e0db-85a5-4e69-9a91-09ef4cd131c5)

I will be creating a pull request for this update, and it would be great if you could check it on your end and proceed from there.
If you are not satisfied, you may assign this to someone else. Thanks for your patience.

**Comment by dhairyagothi** [comment]
> Hey @dhairyagothi . I have implemented the handle register functionality as part of the project. However, I haven't been able to test it on my local server since I don't have MongoDB experience. I have updated the fetch URL to the deployed URL instead.
> 
> ![image](https://private-user-images.githubusercontent.com/120786462/375519104-b485e0db-85a5-4e69-9a91-09ef4cd131c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTQ4NzEsIm5iZiI6MTcyODY1NDU3MSwicGF0aCI6Ii8xMjA3ODY0NjIvMzc1NTE5MTA0LWI0ODVlMGRiLTg1YTUtNGU2OS05YTkxLTA5ZWY0Y2QxMzFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMzQ5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjVhNDZjMThjMzBlN2Y4ZTdmMzMwODA1Mzc3Nzg5ZWY4ODNhNzBiYjIxMjY2NzY3MjNkMjVkNjAzNjNhZWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TkbvgKT4bNddvF7SOy5aopQPjJRzCJtx3dI_Bg_SO6M)
> 
> I will be creating a pull request for this update, and it would be great if you could check it on your end and proceed from there. If you are not satisfied, you may assign this to someone else. Thanks for your patience.

ok i will check it backend is hosted on vercel

**Comment by MohammedJunaid02** [comment]
Hey @dhairyagothi , is this issue resolved completely or not yet. If not yet please assign this to me, i will try to fix it completely.
