### ISSUE TITLE
Create a Station Page 1.0

### ISSUE THREAD

**Issue by Premkolte** [Mehtarishita/StationGuide#105]
# 🖥️ Frontend Issue

### **Description**

Create a station display page.

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### **Expected behavior**

when click on station button on hero page, station selection page should be opened.

### **Actual behavior**

button no working

### **Screenshots or Video**

<img width="1239" alt="Screenshot 2024-10-07 at 1 30 09 PM" src="https://github.com/user-attachments/assets/1a26ef24-4a46-4723-a282-fd40f7c40455">
<img width="1440" alt="Screenshot 2024-10-07 at 1 43 13 PM" src="https://github.com/user-attachments/assets/a1576724-0f24-4644-95f8-fb90558bdc73">

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Assigned @Premkolte can you arrange this alphabetical??

**Comment by Premkolte** [comment]
@dhairyagothi Okk I'll do it in next pr. When I'll add more stations...
