### ISSUE TITLE
[Backend Issue]: Adding Notfications

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#108]
# 🛠️ Backend Issue

### **Description**
A notificaiton should be displayed to the user when they make a booking.

### **Steps to Reproduce**
I will make a notification handler to show the users the confirmation of their bookings.

   
### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by AkshatBari02** [comment]
Please assign this task to me under GSSOC-ext and hactoberfest acepted

**Comment by dhairyagothi** [comment]
> Please assign this task to me under GSSOC-ext and hactoberfest acepted

find a new issue if @haseebzaki-07 not make a PR then i will assign to you
