### ISSUE TITLE
Adding Different page for signin register 

### ISSUE THREAD

**Issue by dhairyagothi** [Mehtarishita/StationGuide#11]
# 🖥️ Frontend Issue

### **Description**

moving this to next page 

![image](https://github.com/user-attachments/assets/90b2a0e7-6ee0-400f-a767-fb14f5ec332e)

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### **Screenshots or Video**

![image](https://github.com/user-attachments/assets/90b2a0e7-6ee0-400f-a767-fb14f5ec332e)

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by sweta123761** [comment]
you can i assign this to me. i can do that using external css

**Comment by dhairyagothi** [comment]
> you can i assign this to me. i can do that using external css

hey @sweta123761 nice to see here . have you check repository ? this issue tells you have to make a different page and in that login and registeration options will be there 
and repo is in reactJS . 
please tell what changes in css you want to make or create a new issue  i will assign to you

**Comment by sweta123761** [comment]
Their is a frontend issue that could be improved . like display of namaste yatri and its adaption to different screen sizes could be improved

**Comment by dhairyagothi** [comment]
> Their is a frontend issue that could be improved . like display of namaste yatri and its adaption to different screen sizes could be improved

Yess sure . Create a new issue please

**Comment by c2gup** [comment]
Hi @dhairyagothi,

I saw that you want to add a new registration page, and you also attached the Figma link in the markdown file. I’ve checked it out, and I’m interested in working on it. Could you please confirm if I only need to add the registration page, or are there other pages I need to add as well?

Here’s the link to the Figma you shared:
https://github.com/dhairyagothi/StationGuide/blob/main/StationGuideFigma.md

Thanks!
Anupam Gupta

**Comment by dhairyagothi** [comment]
> Hi @dhairyagothi,
> 
> I saw that you want to add a new registration page, and you also attached the Figma link in the markdown file. I’ve checked it out, and I’m interested in working on it. Could you please confirm if I only need to add the registration page, or are there other pages I need to add as well?
> 
> Here’s the link to the Figma you shared: https://github.com/dhairyagothi/StationGuide/blob/main/StationGuideFigma.md
> 
> Thanks! Anupam Gupta

pages are already made just want a profile icon and there both options of login and registeration for now
if you can do thell me i will assign to you

**Comment by c2gup** [comment]
Hi @dhairyagothi,

Thank you for confirming! Yes, I can definitely add the profile icon along with the login and registration options.

For the profile icon, can I use the react-icons library, or would you prefer providing a specific icon? Also, regarding the login page, I noticed you mentioned an icon with "Satyamev Jayate" and "Bhartiya Rail." Could you please provide those icons, or let me know where I can find them?

I'm excited to work on this and ensure everything looks perfect!

Looking forward to your response.

Best,
Anupam Gupta

**Comment by anushkaa-dubey** [comment]
Please assign this issue to me  under gssoc and hacktoberfest

**Comment by dhairyagothi** [comment]
ssigned GO ahead @anushkaa-dubey

**Comment by harish08102004** [comment]
Hey @dhairyagothi if this issue is still open I can work on this.
