### ISSUE TITLE
Modification of README.md file(Design), Contributors mention section & Addition of Team section in README.md.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [Mehtarishita/StationGuide#112]
# ✨ Feature Request

## **Description of the Feature**

I want to modify the following things in the README.md file:

### 1) Add animated line separators
Add animated line separators in between sections and also add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution

### 2) Modifiy the **Contributors section**.
Make the Contributors section look more attractive.

### 3) Replace the Contact Information by Adding a **Team section**
The Team section will look more organized and readable.

### 1) Add animated line separators
This will make the README.md file more attractive and improve its readability and usability.

### 2) Modifiy the **Contributors section**.
This will make the Contributors section look more organized and attractive.

### 3) Replace the Contact Information by Adding a **Team section**
This will look professional and will reflect good documentation practices.

### 1) Add animated line separators
![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Modifiy the **Contributors section**.
- Before

![image](https://github.com/user-attachments/assets/d1d1df26-4ac1-4a64-806d-1eb25c635d38)

- After
This is just a template to explain. I will keep the format same as in your repository.
![image](https://github.com/user-attachments/assets/1ec1e50b-fcab-4b4f-8289-8627f108c540)

### 3) Replace the Contact Information by Adding a **Team section**
- Before

![image](https://github.com/user-attachments/assets/41d55918-d909-4e4c-b737-bbb20d331598)

- After
- 
![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

## **Additional Context**

I would like to work on the issues so that I can contribute to making the repository more accessible and friendly for other Contributors.

## **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
how will you going to add contributors automatically ??

**Comment by rajdeepchakraborty-rc** [comment]
> how will you going to add contributors automatically ??

@dhairyagothi First of all thanks for reaching out. Really love Admins who are actively communicating.
So to answer your question, I will be accessing the contributors from your repository from here, which will be updating live:
https://github.com/dhairyagothi/StationGuide/graphs/contributors
And then adding them by changing the UI according to the image provided. This will be a little challenging, but hey, this is the entire point of Open-Source contributions. I came across your project and felt the need to making it more attractive and user-friendly. I would kindly ask you to assign me this task and also add level3.

**Comment by dhairyagothi** [comment]
> > how will you going to add contributors automatically ??
> 
> @dhairyagothi First of all thanks for reaching out. Really love Admins who are actively communicating. So to answer your question, I will be accessing the contributors from your repository from here, which will be updating live: https://github.com/dhairyagothi/StationGuide/graphs/contributors And then adding them by changing the UI according to the image provided. This will be a little challenging, but hey, this is the entire point of Open-Source contributions. I came across your project and felt the need to making it more attractive and user-friendly. I would kindly ask you to assign me this task and also add level3.

no level 3 for documentation changes assigning lv1

**Comment by rajdeepchakraborty-rc** [comment]
Can it not be assigned with level2 at least? Since I am updating two major changes in the documentation to make it more accessible.

**Comment by dhairyagothi** [comment]
> Can it not be assigned with level2 at least? Since I am updating two major changes in the documentation to make it more accessible.

no bro ... readme file is just basic change

**Comment by rajdeepchakraborty-rc** [comment]
Ok thanks for the reply. Will let you know when I raise a PR.

**Comment by rajdeepchakraborty-rc** [comment]
I am working on the issue currently, but had to stop and appreciate the organization of the files. Great work!

**Comment by rajdeepchakraborty-rc** [comment]
Wanted to let you know that I have successfully set up the Contributors section:
![image](https://github.com/user-attachments/assets/d39b2af6-5856-4399-af69-4c5ead1f63fa)
And it is up to date with the repo contributor details:
![image](https://github.com/user-attachments/assets/14b5556a-1bd9-4f08-8e65-fc9ea7c1f36f)

**Comment by rajdeepchakraborty-rc** [comment]
It is looking quite neat and presentable after the change. Do check this and let me know.
![image](https://github.com/user-attachments/assets/892a151d-c5a2-4438-aa50-9db6741e0cc2)

**Comment by rajdeepchakraborty-rc** [comment]
@dhairyagothi I am done with the changes. Have a look at the PR #125 that I have opened for this issue.

https://github.com/user-attachments/assets/d7ec725e-67f7-45f5-91c9-a2ff75f03150

**Comment by rajdeepchakraborty-rc** [comment]
@dhairyagothi wanted to inform you about this:
![image](https://github.com/user-attachments/assets/a4e30e49-5289-4ffd-9581-b0770b9d051a)

The repository is not showing acceptance under the Hacktoberfest program. Please look into this matter.

I looked a bit into the official Hacktoberfest website:
![image](https://github.com/user-attachments/assets/7f30784b-1604-4d45-b749-45cf6ccc487b)

You can also ask the GSSoC core team about this.

**Comment by dhairyagothi** [comment]
Let me merge PR then see @rajdeepchakraborty-rc

**Comment by rajdeepchakraborty-rc** [comment]
@dhairyagothi Thanks once again for reviewing my PR.
