### ISSUE TITLE
Routing to login and register page is not working

### ISSUE THREAD

**Issue by AkshatBari02** [Mehtarishita/StationGuide#113]
# 🐞 Bug Report

### **Describe the bug**
Routing or navigating to login and register pages from register and login pages respectively are not working 

### **Steps to Reproduce**
2. Click on '...'
3. Scroll down to '...'

### **Expected behavior**
Instead of using anchor tag <a></a> Link tag of react should be used to prevent from page from re-loading again and again ans routing can be made perfectly.

### **Actual behavior**
Reloading of page is occurring and error of NOT FOUND is coming

### **Screenshots or Video**
Login:
![image](https://github.com/user-attachments/assets/d2613999-5445-4866-ba2b-bf2333cb2d2a)

Register:
![image](https://github.com/user-attachments/assets/fb713d39-0e2f-4fae-a333-a037ac9386cb)

### **Environment**
Please provide the following details:
- **OS**: _e.g., iOS, Windows, Linux, macOS_
- **Browser/Software**: _e.g., Chrome, Firefox, Node.js_
- **Version**: _e.g., 22.0_

### **Logs & Error Messages**
Not Found

**Comment by dhairyagothi** [comment]
its not working on website but working on local i have already fixed that 
thanku

**Comment by dhairyagothi** [comment]
please raise some different issue

**Comment by dhairyagothi** [comment]
fixed
