### ISSUE TITLE
 no redirect option on login and registration page 

### ISSUE THREAD

**Issue by Mehtarishita** [Mehtarishita/StationGuide#115]
# ✨ Feature Request

### **Description of the Feature**

I will add a back icon as per figma UI . To get back to hero section i will use routes and try some animations to 

Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
yesss yeess @Mehtarishita please add it with routes and make PR asap
