### ISSUE TITLE
Adding routes in login and registration page connection.

### ISSUE THREAD

**Issue by Kajalmehta29** [Mehtarishita/StationGuide#116]
# ✨ Feature Request

### **Description of the Feature**

Login and description page is just connected and not working properly. I will add routes in the pages.

Please assign this issue to me under gssoc'24 EXTENDED and hacktoberfest.

### **Are you participating in GSSoC?**
- [ ] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
noticed that @Kajalmehta29  
please solve it using routes and make PR asap
