### ISSUE TITLE
update front end with  responsive 

### ISSUE THREAD

**Issue by Ek-ta-bharti** [Mehtarishita/StationGuide#119]
# 🖥️ Frontend Issue

There is an issue with the Navbar on the side, and the entire UI is messed up. I can fix it. Please grant me access so I can resolve the issue

![Screenshot 2024-10-07 231508](https://github.com/user-attachments/assets/1eb5ad1a-6c5a-4e9d-9871-6555798be513)

### Are you participating in GSSoC?
yes

**Comment by dhairyagothi** [comment]
which part you want to fix ??
there is already a issue for hamburger

**Comment by Ek-ta-bharti** [comment]
I will fix the aside navigation bar, select language section, navigation booking station, 3D map, schedule, notifications, and contribution sections because they are not aligned and are overlapping with the chatbot. Please let me know what level of access I need to proceed

**Comment by dhairyagothi** [comment]
@Ek-ta-bharti have you checked stationguidefigma.md 
I want that in responsiveness 

Change chatbot icon position

**Comment by Ek-ta-bharti** [comment]
@dhairyagothi  Alright, I'll take care of that. Could you let me know my level for this?

**Comment by dhairyagothi** [comment]
@Ek-ta-bharti you want to change UI or code of website ?? 

Level i will decide after seeing no of changes made in PR

**Comment by Ek-ta-bharti** [comment]
ui and code both

**Comment by dhairyagothi** [comment]
@Ek-ta-bharti any updates don't change Figma UI
