### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by PankajKumardev** [Mehtarishita/StationGuide#120]
I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .
Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

[x ] I am contributing under GSSoC-ext
[x ] I am contributing under hacktoberfest

**Comment by dhairyagothi** [comment]
what will docker file contain ??

**Comment by PankajKumardev** [comment]
Frontend Dockerfile: Runs npm run dev for React with hot-reloading.
Backend Dockerfile: Runs npm run dev with nodemon for backend auto-reloading. 
and need of docker because  it Avoid installing extra tools like Node.js manually and Keep setup simple on any computer.

**Comment by dhairyagothi** [comment]
Okay make PR then i will see
