### ISSUE TITLE
Addition of a contact page and about us page

### ISSUE THREAD

**Issue by Mahy-31** [Mehtarishita/StationGuide#124]
There is no contact and about us page. The website will look complete once we add them. I believe as a UI/UX designer and web developer, I can create an attractive about us and contact page for you. Could you please assign me this task?

**Comment by dhairyagothi** [comment]
@Mahy-31 add only about us page for now

**Comment by Mahy-31** [comment]
> @Mahy-31 add only about us page for now

Yes sure. Where can I get those informations?

**Comment by dhairyagothi** [comment]
> > @Mahy-31 add only about us page for now
> 
> Yes sure. Where can I get those informations?

add on your own from this 

![Screenshot 2024-09-21 151104](https://github.com/user-attachments/assets/9be25fb1-ef5a-4512-bc3d-8147403a7f86)

**Comment by Mahy-31** [comment]
Okey. Thank you

**Comment by meghanakn473** [comment]
hey @dhairyagothi can u assign me this issue ?

**Comment by dhairyagothi** [comment]
@Mahy-31 any updates

**Comment by dhairyagothi** [comment]
@meghanakn473 make only about us page

**Comment by Mahy-31** [comment]
> @Mahy-31 any updates

I'm on it

**Comment by meghanakn473** [comment]
> > @Mahy-31 any updates
> 
> I'm on it

i hv made the pr already ;)

**Comment by dhairyagothi** [comment]
> > @Mahy-31 any updates
> 
> I'm on it

create PR i will check it

**Comment by dhairyagothi** [comment]
beest one i wiill keep

**Comment by meghanakn473** [comment]
It's already merged ../
