### ISSUE TITLE
MAKING A TICKET BOOKING PAGE

### ISSUE THREAD

**Issue by RAJIV81205** [Mehtarishita/StationGuide#127]
# 🖥️ Frontend Issue

### **Description**
THE BOOKING OPTION SHOULD REDIRECT  THE USER TO A PAGE TO INPUT DETAILS WHERE THEY WANT TO TRAVEL ON WHAT DATE

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/28b32dc3-efa9-4349-bd49-f51acde01de8)

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
already a same issue #51
