### ISSUE TITLE
Adding login and register feature

### ISSUE THREAD

**Issue by Gauravtb2253** [Mehtarishita/StationGuide#13]
# ✨ Feature Request

### **Description of the Feature**
I can add login and register functionality to the website.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Hey @Gauravtb2253 
Its already there can you please tell me in detail what contribute you want to make ?

**Comment by Suhas-Koheda** [comment]
Hey @dhairyagothi  I would like to add the back-end part to the login and signup under gssco24 extd and hacktober fest can you assign it to me?

**Comment by dhairyagothi** [comment]
> Hey @dhairyagothi  I would like to add the back-end part to the login and signup under gssco24 extd and hacktober fest can you assign it to me?
> 

@Suhas-Koheda please wait for update from @Gauravtb2253 .

Until then find some different issue .

**Comment by Gauravtb2253** [comment]
Actually it is not present in the repo so I could add it for the user to register and login to the system

**Comment by dhairyagothi** [comment]
> Actually it is not present in the repo so I could add it for the user to register and login to the system

files are already there check it sign in and registeration. i am not clear what contribution you want to make please share some ss if possible

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..

**Comment by dhairyagothi** [comment]
@SaanyaGarg5 its already added thanku please make other issue
