### ISSUE TITLE
Integrate Google and Facebook-Oauth in signup page

### ISSUE THREAD

**Issue by srivastav2006** [Mehtarishita/StationGuide#133]
# ✨ Feature Request

### **Feature Description**
Add Google and Facebook OAuth on the signup page to allow users to register and log in using their social accounts.

### **Problem Statement**
The current signup process is limited to email registration, which may discourage users. Social logins will enhance user convenience and boost signup rates.

### **Proposed Solution**
Add "Sign up with Google" and "Sign up with Facebook" buttons on the signup page, enabling single-click registration via OAuth.

### **Alternatives Considered**
- Implementing only one OAuth option.
- Exploring other social platforms like Twitter or Apple, but focusing on Google and Facebook due to larger user bases.

**Comment by dhairyagothi** [comment]
go for it @srivastav2006

**Comment by tarunkumar2005** [comment]
Assign this to me under gssoc 2024 ext and hacktoberfest i will work on it.

**Comment by dhairyagothi** [comment]
@tarunkumar2005 start working

**Comment by tarunkumar2005** [comment]
@dhairyagothi Bro you have added phone number to signup page google auth doesn't provide phone number can i remove that or make it optional is it okay
