### ISSUE TITLE
the register does not create any Username but login ask for Username

### ISSUE THREAD

**Issue by Kratik1093** [Mehtarishita/StationGuide#135]
# 🐞 Bug Report

### **Describe the bug**
if no user name is created then how will some one use while login

### **Steps to Reproduce**
2. Click on '...'
3. Scroll down to '...'

### **Expected behavior**
should allow creating username 

### **Screenshots or Video**
![Screenshot 2024-10-08 181147](https://github.com/user-attachments/assets/350fe2db-58a4-44a5-962f-9b2faf671212)
![Screenshot 2024-10-08 181202](https://github.com/user-attachments/assets/a8ce2bbf-a110-489a-a966-2fedbe1d6e1b)

### **Environment**
Please provide the following details:
- **OS**: Windows
- **Browser/Software**: microsoft edge
- **Version**: _e.g., 22.0_

**Comment by dhairyagothi** [comment]
just few line of changes do it  annd it will be good if you can addd some animation or other things
