### ISSUE TITLE
UI of Select language button must be changed

### ISSUE THREAD

**Issue by nishtha-902** [Mehtarishita/StationGuide#136]
# 🖥️ Frontend Issue

### **Description**
Select language button must be enhanced

### **Expected behavior**
Button must have dropdown and logo in same line

### **Actual behavior**
Button have dropdown and logo in different line

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/01ce7412-1da4-4326-a2f6-603ea3270e86)

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
same issue as #77  comment there i will assign
