### ISSUE TITLE
Add eye icon on login page

### ISSUE THREAD

**Issue by AyushSharma72** [Mehtarishita/StationGuide#137]
add eye icon to show and hide password on login page

![image](https://github.com/user-attachments/assets/129bed78-9ef9-4be6-8d01-b00f736dc9b8)

**Comment by AyushSharma72** [comment]
please add gssoc-ext label @dhairyagothi

**Comment by dhairyagothi** [comment]
> please add gssoc-ext label @dhairyagothi 

You make PR nothing matters with issue
