### ISSUE TITLE
Add home page navigation button stations page

### ISSUE THREAD

**Issue by AyushSharma72** [Mehtarishita/StationGuide#139]
the station page do not have any button to navigate back to home i want to add a button so that user can go back to the home page 

![image](https://github.com/user-attachments/assets/8029f068-3d09-4f59-9ad2-5eee5abc44e3)

please assign this issue to  me @dhairyagothi

**Comment by dhairyagothi** [comment]
Add back icon similar to login signup page @AyushSharma72

**Comment by RiddhiM170904** [comment]
its not working @dhairyagothi i can fix it please assign me

**Comment by dhairyagothi** [comment]
yes please @RiddhiM170904 noticed that
