### ISSUE TITLE
improving the placement of namaste sarthi in different layouts

### ISSUE THREAD

**Issue by sweta123761** [Mehtarishita/StationGuide#14]
# 🖥️ Frontend Issue

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Great @sweta123761 

This is your first time open source contribution i think .... 
Just make sure to add some discription also and add relevant screenshot for better understanding 

Assigning you
Leeeesss gooo ... 
Please update me with work within 24 hours

**Comment by sweta123761** [comment]
ok thankyou
