### ISSUE TITLE
Add state wise filter in the station page

### ISSUE THREAD

**Issue by PraveenUppar** [Mehtarishita/StationGuide#140]
# ✨ Feature Request

### **Description of the Feature**
Add a filter on the station page that allows users to filter stations based on the state they are located in. This will help users find stations in a specific region more easily.

### **Problem Statement**
Currently, users may find it difficult to search for stations based on their geographic location. Adding a state-wise filter will make it easier to locate stations in the desired state, improving user experience and navigation.

### **Proposed Solution**
Implement a drop-down or multi-select filter on the station page that allows users to choose one or multiple states. Based on the selection, the list of stations will dynamically update to show only those that are located in the selected state(s). 

![Screenshot 2024-10-08 222117](https://github.com/user-attachments/assets/856663c7-8165-4948-a0a3-6fca795d589a)

### **Alternatives Considered**
None

### **Additional Context**
None

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Go ahead @PraveenUppar
