### ISSUE TITLE
Login and signup pages have a bug on the switch links

### ISSUE THREAD

**Issue by tarunkumar2005** [Mehtarishita/StationGuide#141]
# 🐞 Bug Report

### **Describe the bug**
So as you can see on the login and signup pages there is option to switch to login or signup right already have a account? login and so they have underline which shouldn't be there and it should be fixed.

### **Expected behavior**
Underline should not be there.

### **Actual behavior**
Underline is there

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/8a57446c-3213-4491-a21c-09d4f7d0e064)

@dhairyagothi Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by dhairyagothi** [comment]
What do you want to fix in this ? @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@dhairyagothi See there is a underline on the Register it is a default behaviour of the a tag but there shouldn't be a underline like that it needs to be fixed. see in a fully launched website there is nothing like this.

**Comment by dhairyagothi** [comment]
its fine bro no change needed in that
