### ISSUE TITLE
Signup with google is not there

### ISSUE THREAD

**Issue by tarunkumar2005** [Mehtarishita/StationGuide#142]
# ✨ Feature Request

### **Description of the Feature**
So right now in the login and signup pages the login with google or signup with google option isn't there which should not be the case there should be various options to signup and signin okay.

### **Problem Statement**
Already explained that google signup or login isn't there.

### **Proposed Solution**
Adding google signup and login feature.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

@dhairyagothi Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by dhairyagothi** [comment]
There is similar issue @tarunkumar2005 please wait until updates from that issue you can comment it there. Check issues
