### ISSUE TITLE
Fixing the position of the arrow icon on the login and signup pages

### ISSUE THREAD

**Issue by tarunkumar2005** [Mehtarishita/StationGuide#143]
# 🐞 Bug Report

### **Describe the bug**
So right now the arrow icon is not at the top which should not be the case as arrow button should always be in top irrespective of the content on the page.

### **Expected behavior**
Arrow icon position

### **Actual behavior**
It should be at the top of the page

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/fad8c444-5023-4e72-8f8d-ba50235adc86)

@dhairyagothi Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by arpit74170** [comment]
Assign this task to  me i will fix it

**Comment by AKSHITHA-CHILUKA** [comment]
@dhairyagothi Please assign it to @tarunkumar2005

**Comment by dhairyagothi** [comment]
Assigned @tarunkumar2005

**Comment by dhairyagothi** [comment]
> @dhairyagothi Please assign it to @tarunkumar2005

Done

**Comment by AKSHITHA-CHILUKA** [comment]
Thanks @dhairyagothi
