### ISSUE TITLE
Adding the contributors page where we will display all the contributors who have contributed to this.

### ISSUE THREAD

**Issue by tarunkumar2005** [Mehtarishita/StationGuide#144]
# ✨ Feature Request

### **Description of the Feature**
Adding the contributors page where we will display all the contributors who have contributed to this. So that they have  visbility too and people can get a view who have contributed to this website as it is a open source.

### **Problem Statement**
No contributors page.

### **Proposed Solution**
Adding the contributors page.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

@dhairyagothi Assign this to under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by dhairyagothi** [comment]
Yess go ahead @tarunkumar2005 make according to UI
