### ISSUE TITLE
CONFIRMATION MSG ON REGISTER

### ISSUE THREAD

**Issue by Ishika-Gupta06** [Mehtarishita/StationGuide#145]
# ✨ Feature Request

### **Description of the Feature**
It provides a confirmation upon successful registering

Better User Experience

### **Additional Context**
![Screenshot 2024-10-09 000309](https://github.com/user-attachments/assets/3467be37-6bc8-40ec-bf7a-e1fff905479c)

### **Are you participating in GSSoC?**
- [X ] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
go for it @Ishika-Gupta06 make a PR after changes
