### ISSUE TITLE
[Backend Issue]: No Login/SignUp backend logic

### ISSUE THREAD

**Issue by tarunkumar2005** [Mehtarishita/StationGuide#15]
# 🛠️ Backend Issue

### **Description**
I saw there is no proper backend for signup and login. I would like to contribute to this. Assign me on this under GSSOC'24 extd and hacktoberfest'24. I am a mern stack web developer. I will be using proper and professional backend setup.
   
### Tech stack required 
Express.js 
mongodb

### **Are you participating in GSSoC?**
Yes

**Comment by dhairyagothi** [comment]
good issue please go ahead and try to complete it asap @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@dhairyagothi Can i talk to you i need to confirm some things related to the backend logic. reply ASP how can i connect with you or contact you.

**Comment by dhairyagothi** [comment]
> @dhairyagothi Can i talk to you i need to confirm some things related to the backend logic. reply ASP how can i connect with you or contact you.

sure connect with me on LinkedIn or discord 
https://www.linkedin.com/in/dhairya-gothi/
