### ISSUE TITLE
remove unused dependencies

### ISSUE THREAD

**Issue by AyushSharma72** [Mehtarishita/StationGuide#150]
your backend package.json file have a lot of unused dependencies which are not used in the project but increase the size of the nodemodules 

here is a list of those :
![Screenshot (190)](https://github.com/user-attachments/assets/beff1cf2-c6df-4d8b-a31a-c99d14e7f4ff)

image 2 :

![image](https://github.com/user-attachments/assets/36c81ed2-12a9-4043-a2e2-32ca9a8226ec)

please assign me the issue to make you nodemodules light weight
@dhairyagothi

**Comment by dhairyagothi** [comment]
The list shows mongoDB but it is in use @AyushSharma72

**Comment by AyushSharma72** [comment]
> The list shows mongoDB but it is in use @AyushSharma72

You are using mongoose  for database connection not mongodb both are different 
Also if after removing any dependencies there will be an error I will add it again 
@dhairyagothi 

![image](https://github.com/user-attachments/assets/253401f8-2488-4cc5-90b1-7a11d1dbfc62)

**Comment by dhairyagothi** [comment]
Ok ok
