### ISSUE TITLE
Making new routes necessary from the landing page , and add some code in the new pages that were empty for initial period , and made half of the buttons go to their respective routes

### ISSUE THREAD

**Issue by Raja-Abrar-Khan** [Mehtarishita/StationGuide#152]
# 🖥️ Frontend Issue

### **Description**
In this Pr i made all the routes necessary from the landing page , and add some code in the new pages that were empty for initial period , and i added some codes in the new pages and make half of the buttons navigate to their respective pages.
in my next pr i will make the other remaining buttons go to their respective button and in half of the buttons , now if you click in the image it will navigate to the respective route . In My next pr i will make the other buttons to work like this too. Will make steady changes and make this project better.

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
all routes are upadted
