### ISSUE TITLE
Create and use strong passwords

### ISSUE THREAD

**Issue by Ishika-Gupta06** [Mehtarishita/StationGuide#157]
# ✨ Feature Request

### **Description of the Feature**
Password security starts with creating a strong password.

### **Problem Statement**
creating a strong password for avoid account hacking.

### **Proposed Solution**
At least 12 characters long but 14 or more is better.

A combination of uppercase letters, lowercase letters, numbers, and symbols.

Not a word that can be found in a dictionary or the name of a person, character, product, or organization.

Significantly different from your previous passwords.

### **Are you participating in GSSoC?**
- [X ] Yes
- [ ] No

**Comment by Ishika-Gupta06** [comment]
@dhairyagothi **please assign me this under GSsoc-ext, hacktoberfest, level-1,2,3**

**Comment by dhairyagothi** [comment]
Assigned @Ishika-Gupta06
