### ISSUE TITLE
SIgnup error

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#158]
# 🐞 Bug Report

### **Describe the bug**
user does not sing-up after filling out the rnecessary fields 

### **Steps to Reproduce**
1. Go to signup page
2. FIll the fields
3. Click on Register

### **Expected behavior**
Ideally user should be registered or error should be displayed with proper message.

### **Environment**
Please provide the following details:
- **OS**: _e.g., iOS, Windows, Linux, macOS_
- **Browser/Software**: _e.g., Chrome, Firefox, Node.js_
- **Version**: _e.g., 22.0_

**Comment by dhairyagothi** [comment]
its working in local backend is not connected in deployment

**Comment by haseebzaki-07** [comment]
@dhairyagothi You can have it in production as well if database is the need we can get some free databases to start with.

**Comment by dhairyagothi** [comment]
@haseebzaki-07 a same issue already there and he is making PR will let you know once he is done

**Comment by haseebzaki-07** [comment]
sure

**Comment by dhairyagothi** [comment]
completed
