### ISSUE TITLE
Improving Home Page 

### ISSUE THREAD

**Issue by Suhas-Koheda** [Mehtarishita/StationGuide#16]
# ✨ Feature Request

### **Description of the Feature**
Changing the home page layout and then adding responsiveness to the footer and 
Basically a revamp of home page

### **Problem Statement**
the white background overlaps with image 
the font colors and buttons are not visually aesthetic

### **Proposed Solution**
Add visually appealing font colors and add responsiveness to the footer like a nav menu rather than like that 

### **Alternatives Considered**
Nothing

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by Suhas-Koheda** [comment]
@dhairyagothi can you look into it and assign it to me under gssoc24 extnd and hacktoberfest

**Comment by dhairyagothi** [comment]
> @dhairyagothi can you look into it and assign it to me under gssoc24 extnd and hacktoberfest


@Suhas-Koheda assigning but make sure that UI will be same as `StationGuidefigma.md`

**Comment by Suhas-Koheda** [comment]
but the one you gave is for mobile one 
i would be adding some gradients if it looks good

**Comment by dhairyagothi** [comment]
> but the one you gave is for mobile one i would be adding some gradients if it looks good

sure make PR after changes then i will tell but keep basic structure same like colour theme and all

**Comment by Pranith-Kantamneni** [comment]
@dhairyagothi can you please assign this to me 
we both will be working together @Suhas-Koheda

**Comment by dhairyagothi** [comment]
@Suhas-Koheda whats the update ?

**Comment by bhogalesiddhi** [comment]
Hey, can you please assign this to me i will start working on it right now!

**Comment by dhairyagothi** [comment]
Assigned @bhogalesiddhi

**Comment by dhairyagothi** [comment]
@bhogalesiddhi any updates?

**Comment by dhairyagothi** [comment]
No updates closing issue for now
