### ISSUE TITLE
Contact us Page

### ISSUE THREAD

**Issue by Premkolte** [Mehtarishita/StationGuide#162]
# 🖥️ Frontend Issue

### **Description**

contact us page having major contact details

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### **Screenshots or Video**

ill attach in pr

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
make proper issue with giving complete details @Premkolte

**Comment by Premkolte** [comment]
> make proper issue with giving complete details @Premkolte

Ok, I'll keep it in mind next time.
@dhairyagothi
