### ISSUE TITLE
Want to add the progress bar

### ISSUE THREAD

**Issue by srishti023** [Mehtarishita/StationGuide#164]
# ✨ Feature Request

### **Description of the Feature**
The site has no progress bar iwant to add this feature to your page.
### **Proposed Solution**
Whenever the user comes and scrolls the website the progress bar increase or decrease on the basis of user's position on the page. It shows visually to user where he or she scrolls.

### **Are you participating in GSSoC?**
Yes

**Comment by dhairyagothi** [comment]
@srishti023 where you want to add ??in which page ?

**Comment by srishti023** [comment]
I propose adding a progress bar to the Stations page. This will visually indicate the user’s navigation progress, enhancing the overall experience. It can help users track their movement across the page and make the interface more engaging.

HERE,
https://github.com/user-attachments/assets/eaafaaaa-9e3a-4b25-b97c-192df63299a6
