### ISSUE TITLE
[Backend Issue]: Add Nodemon

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#168]
# 🛠️ Backend Issue

### **Description**
I want to add Nodemon in the backend to support hot-reloading for backend building . It will be greate upgrade upon "node index.js"

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
already there bro

**Comment by haseebzaki-07** [comment]
@dhairyagothi I have searched the project and did not find nodemon also the project starts with "node index.js"

![Screenshot 2024-10-10 153800](https://github.com/user-attachments/assets/140bf9f3-2ff7-4cdb-946c-53130d2135a3)

If I am right then please open the issue as I want to work on it.
