### ISSUE TITLE
WANT TO CHANGE UI LIKE ADDING HOVER AND THERE IS A BUG IN THE GOOGLE TRANSLATE SECTION.

### ISSUE THREAD

**Issue by HimangshuSharma01** [Mehtarishita/StationGuide#169]
# 🖥️ Frontend Issue

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### **Screenshots or Video**
https://github.com/user-attachments/assets/c1580318-e52f-4d2c-a663-e08c69421838

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
There is a similar issue for google translator you add hover options only
