### ISSUE TITLE
Password being logged in the Browser console

### ISSUE THREAD

**Issue by MihirSaiDudekula** [Mehtarishita/StationGuide#17]
# 🖥️ Frontend Issue

### **Description**
 This issue addresses the security concern of passwords being logged in the browser console during user interactions.

### **Steps to Reproduce**

1. Click on Login or Register
2. Fill in your credentials
3. Click on submit
4. check your browsers console

### **Expected behavior**
Password and username shouldnt be visible

### **Actual behavior**
They are visible

### **Screenshots or Video**

![image](https://github.com/user-attachments/assets/3322b4fd-900a-46a6-af9a-0c56dea9970a)

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by MihirSaiDudekula** [comment]
@dhairyagothi, could you please take a look at this and assign it to me for GSSoC 2024 and Hacktoberfest? Thank you!

**Comment by dhairyagothi** [comment]
ohhh that's great but it will change when we add backend in this file 
good issue do this for now

**Comment by MihirSaiDudekula** [comment]
> ohhh that's great but it will change when we add backend in this file good issue do this for now

Kind of saw that coming haha
Thanks, ill fix it anyway

**Comment by dhairyagothi** [comment]
> > ohhh that's great but it will change when we add backend in this file good issue do this for now
> 
> Kind of saw that coming haha Thanks, ill do it anyway

ya do for now

**Comment by MihirSaiDudekula** [comment]
@dhairyagothi  PR added , please acknowledge
