### ISSUE TITLE
adding preloader in website 

### ISSUE THREAD

**Issue by Mehtarishita** [Mehtarishita/StationGuide#170]
# 🖥️ Frontend Issue

### **Description**

 i will add similar pre loader as in figma design with all animations please assign me this under gssoc'24 EXTENDED and hacktoberfest

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Go ahead and add animations please

**Comment by srishti023** [comment]
Please assign me this issue. I will do it and add animation too
