### ISSUE TITLE
Add 3D map 

### ISSUE THREAD

**Issue by PraveenUppar** [Mehtarishita/StationGuide#177]
# ✨ Feature Request

### **Description of the Feature**
Add Google map to the 3D-map section

### **Problem Statement**
Missing map in 3D map section

### **Proposed Solution**
Add google map in the 3D map section

![Screenshot 2024-10-10 202712](https://github.com/user-attachments/assets/7809c671-4698-4740-897f-69d2c6ea999e)

### **Alternatives Considered**

None
### **Additional Context**
None

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
do you know how to use MAPBox ??

**Comment by PraveenUppar** [comment]
i was doing with google api

**Comment by PraveenUppar** [comment]
google map api is now free

**Comment by dhairyagothi** [comment]
we are thinking to  make 3d models of station

**Comment by PraveenUppar** [comment]
ok i will try with MAPbox and raise PR

**Comment by PraveenUppar** [comment]
For Mapbox it is asking for linking bank account I tried but my card is not supporting
do you have account ?

**Comment by PraveenUppar** [comment]
shall i add the map in the navigation in the 3d map section ?
