### ISSUE TITLE
Making of Navigion page 

### ISSUE THREAD

**Issue by Raja-Abrar-Khan** [Mehtarishita/StationGuide#178]
# ✨ Feature Request

### **Description of the Feature**
I will work on making platform navigation page as in the Figma design of Website will make steady progress to make it work better and better with every PR.Earlier By mistake i made train navigation but now i have seen the figma design i have understood what is required Thanks to @dhairyagothi .

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by Raja-Abrar-Khan** [comment]
@dhairyagothi  assign this issue to me

**Comment by dhairyagothi** [comment]
what is navigion ?

**Comment by dhairyagothi** [comment]
how will you add navigation of a platform ammeneties ?

**Comment by Raja-Abrar-Khan** [comment]
![Screenshot 2024-10-10 220428](https://github.com/user-attachments/assets/eda85400-f385-4a6d-b046-439e43d70d44)
this is the figma design you have created yourself of navigation page

**Comment by Raja-Abrar-Khan** [comment]
For the first pull request (PR), I'll focus on building the foundational structure of the platform navigation interface. This will include setting up the map component using Mapbox, creating the basic layout for the navigation form (for selecting origin and destination), and rendering a platform list with placeholder data. In this phase, I’ll ensure the app layout is responsive and the core components are properly integrated with basic functionality. For the next PR, I’ll enhance the navigation experience by adding real-time data for platform status, improving interactivity, and incorporating location-based services like GPS for automatic location detection.

**Comment by dhairyagothi** [comment]
@Raja-Abrar-Khan go ahead and make with figma design 
i will assign level after seeing changes in PR

**Comment by Raja-Abrar-Khan** [comment]
Sure bro will work in steps as i tell you above
