### ISSUE TITLE
Want to add a Rate Us feature.

### ISSUE THREAD

**Issue by Suvadip-sana** [Mehtarishita/StationGuide#182]
# ✨ Feature Request

### **Description of the Feature**

I want to add a **Rate Us** feature for this web platform.

### **Problem Statement**

In this type of web platform there should be a feature like **Rate Us**. It help the developer for further update or feature addition.

### **Proposed Solution**

I make a feature of **Rate Us** 
where user can give stars btw 1 to 5 with a cool UI as you seen on the attatched screen recording.
and also user can submit there thought through comment.

### **Additional Context**

https://github.com/user-attachments/assets/a78b98e2-782c-4b2f-94a3-d163f7c8140c

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
add in hamburger
