### ISSUE TITLE
I want to made a small change met in code for navigation bar language selection tab.

### ISSUE THREAD

**Issue by Piyushsahu99** [Mehtarishita/StationGuide#185]
**# 🐞 language selection box is too big**

### **This is the bug which i found** 

![Screenshot 2024-10-11 063445](https://github.com/user-attachments/assets/0b68669d-a5e3-4ea4-83fe-4353a9553fef)

and i want a little changement in code to fix this issue
can you pls assign this to me.

### **how it look after fixing it 👍:** 

![Screenshot 2024-10-11 063937](https://github.com/user-attachments/assets/35b50f5b-90df-49c4-857c-c2caa9c9c019)

**Comment by dhairyagothi** [comment]
i want you to change complete css of google translator and make it look more good
