### ISSUE TITLE
No Home page button is availible to reurn to the previous page .

### ISSUE THREAD

**Issue by Piyushsahu99** [Mehtarishita/StationGuide#186]
# ✨ I want to add a button ( arrow on top of navigation bar) to get return to the previous page 

### **This is the issue i arrised :**

![Screenshot 2024-10-11 065421](https://github.com/user-attachments/assets/57f7ed51-5d95-4748-9ddf-c3c4c0dd9359)

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
@Piyushsahu99 webssite in progresss that will be add while making pages . i think this issue should be hold for a while. thankyou
