### ISSUE TITLE
MAKING THE SCHEDULES WEBSITE BETTER

### ISSUE THREAD

**Issue by RAJIV81205** [Mehtarishita/StationGuide#187]
# ✨ Feature Request

### **Description of the Feature**
I WANT TO ADD THE SCHEDULE OF EVERY STATION IN THA WEBPAGE. USER HAS TO CLICK ON THEIR RESPECTIVE STATION AND IT WILL SHOW ALL THE SCHEDULE OF THAT STATION

### **Problem Statement**
IT WILL HELP USERS TO GET THE SCHEDULE OF EVERY STATION

### **Proposed Solution**
ADDING THE DATA OF EVERY STATION

### **Additional Context**
![image](https://github.com/user-attachments/assets/f3857152-811d-42cf-9d35-824803a5e939)

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
make complete page according to UI @RAJIV81205 .

**Comment by RAJIV81205** [comment]
OKAY , GIVE ME SOME TIME
