### ISSUE TITLE
Changing the colour of the scrollbar

### ISSUE THREAD

**Issue by SrijaVuppala295** [Mehtarishita/StationGuide#188]
# ✨ Feature Request

### **Description of the Feature**

This feature request proposes adding the ability to customize the color of the scrollbar on the website. The aim is to improve the user interface by making the scrollbar more visually appealing and aligned with the overall design theme of the website.

### **Problem Statement**

The default scrollbar may not blend well with the website’s theme, leading to a break in the visual flow. Customizing the scrollbar color would enhance the user experience by offering a more cohesive and modern design.

### **Proposed Solution**

Implement custom scrollbar styling using CSS. 

### **Alternatives Considered**

An alternative approach could be allowing users to switch between pre-defined themes that adjust the scrollbar color accordingly. However, this might require more complex theming options to be implemented.

### **Additional Context**
Customizing scrollbars is supported by most modern browsers. However, fallback styles might be necessary for browsers that do not support it (like Firefox without the CSS scrollbar module).

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
altough this is single pagw website but do it and add same colours as theme

**Comment by SrijaVuppala295** [comment]
Sure!! @dhairyagothi
