### ISSUE TITLE
Adding the calender option in Station Services

### ISSUE THREAD

**Issue by SrijaVuppala295** [Mehtarishita/StationGuide#189]
# ✨ Feature Request

### **Description of the Feature**

![image](https://github.com/user-attachments/assets/294cd6c5-db78-487f-8a54-7e73af6f5e90)

Here I want to add the mini calender so the users can choose the date and time from that calendar.

### **Problem Statement**
Adding calender option to  users so that they can  easily select dates and times via a graphical interface, improving the user experience for booking, scheduling, or other time-based interactions.

### **Proposed Solution**
Using a custom calendar component from scratc

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
assigned @SrijaVuppala295
