### ISSUE TITLE
Creating Contact Us page in the Hamburger menu

### ISSUE THREAD

**Issue by SrijaVuppala295** [Mehtarishita/StationGuide#190]
# ✨ Feature Request

### **Description of the Feature**
This feature aims to add a "Contact Us" page accessible through the hamburger menu. The page will contain a form where users can fill in their contact details and messages, along with any additional relevant information.

### **Problem Statement**
Currently, there is no easy way for users to reach out or submit queries. Adding a "Contact Us" page will enhance user interaction, allowing them to directly get in touch for support, feedback, or inquiries.

### **Proposed Solution**
![image](https://github.com/user-attachments/assets/cc1ed631-9511-44df-9092-42a73f1c8af3)

Add a "Contact Us" link to the hamburger menu.
On click, redirect users to a new page that contains a simple contact form.
The form will include fields like Name, Email, Message, and possibly a phone number.
Include a "Submit" button that will send the data to the backend for further processing.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
already there bro just it is not showing on clicking completed by a PR yesterday
