### ISSUE TITLE
Changing the title according to the page!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [Mehtarishita/StationGuide#191]
# ✨ Feature Request

### **Description of the Feature**
This feature involves dynamically changing the browser tab's title based on the page the user is viewing. For example, when navigating between different sections like "Home," "About Us," or "Contact Us," the title of the page should reflect the current content.  Like Example : Station Saarthi | Notifications
                                       Station Saarthi | Contact Us 
                                       Station Saarthi | Login or Register 
### **Problem Statement**

Currently, the browser tab shows a static title regardless of the page being viewed. This can lead to confusion and doesn't provide users with immediate context about the page they are on. Dynamic titles will enhance navigation and user experience by reflecting the content or section.

### **Proposed Solution**

For single-page applications (SPAs), use the router to update the title on route change.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
great add @SrijaVuppala295
