### ISSUE TITLE
Input search bug

### ISSUE THREAD

**Issue by STXRSHIVA** [Mehtarishita/StationGuide#195]
once i click on the search it enlarges and when i dont it still remains the same 

![Screenshot 2024-10-11 185343](https://github.com/user-attachments/assets/276fb58a-bbd2-4f06-ad4a-6f04d9747e84)

![Screenshot 2024-10-11 185349](https://github.com/user-attachments/assets/1cff2124-20ca-44a2-96a3-8a4c128309ea)

please assign me this

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
