### ISSUE TITLE
I want to add all the railway station of the india.

### ISSUE THREAD

**Issue by Vaibhav-Samdani** [Mehtarishita/StationGuide#196]
# ✨ Feature Request

### **Description of the Feature**
I want to add all the railway station of the india in Station's section.

### **Problem Statement**
It has limited stations.

### **Proposed Solution**
I have data of all the station available in india.

### **Are you participating in GSSoC?**
- [x] Yes

- Want to work on this issue.
- Also participating in hacktoberfest. 
- Please add level3 tag for the issue.

**Comment by dhairyagothi** [comment]
it will be great if you add this using API and also keep sorting according to state remains same

**Comment by Vaibhav-Samdani** [comment]
please add level3 tag to the issue!

**Comment by dhairyagothi** [comment]
> please add level3 tag to the issue!

level on issue not matters that much
