### ISSUE TITLE
Enhancing the Google Translate Box 

### ISSUE THREAD

**Issue by AsifQamar** [Mehtarishita/StationGuide#197]
enhancing the google translate box for better user experience
Piority - Medium
@dhairyagothi Please assign me issue under Gssoc and Hacktober tag
<img width="960" alt="Screenshot_145" src="https://github.com/user-attachments/assets/8c5db14d-cd5d-4d97-a7bf-a44ac330b239">

**Comment by dhairyagothi** [comment]
a same issue #114 already exists comment there
