### ISSUE TITLE
Adding contributor icons in readme file.

### ISSUE THREAD

**Issue by Mehtarishita** [Mehtarishita/StationGuide#20]
# ✨ Feature Request

### **Additional Context**

Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.
### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Intresting @Mehtarishita 
go ahead make PR asap
