### ISSUE TITLE
Adding a schedule page 

### ISSUE THREAD

**Issue by Mayanksaininh** [Mehtarishita/StationGuide#201]
# ✨ Feature Request

### **Description of the Feature**
Schedule page is empty. There should be description about the trains from the given station.

### **Problem Statement**
Nothing in the schedule page   

### **Proposed Solution**
I will add the description of evert train form the station and provide the timing of train 

### **Additional Context**

![Screenshot (13)](https://github.com/user-attachments/assets/65c77a18-0342-4449-b6e3-0cca9fb336c8)
![Screenshot (14)](https://github.com/user-attachments/assets/883442db-eb8d-430e-8ae7-d3f6de12f058)
 

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by Mayanksaininh** [comment]
Please assign this issue to me.

**Comment by dhairyagothi** [comment]
@Mayanksaininh always give proper discription of your issue . how can i understand just by seeing title of issue , tell in detail about issue with some ss and proposed solution

**Comment by Mayanksaininh** [comment]
I added ss and complete description of my issue, I also checked for 3 time
after raise this issue but not showing any ss and description I don't know
why
I think, if I create bug instead of feature request then all ss and
description will you show .

**Comment by Mayanksaininh** [comment]
I added all the ss regarding my issue so now please assign this issue to me

**Comment by Mayanksaininh** [comment]
Please see this as soon as possible

**Comment by dhairyagothi** [comment]
how will you add this ?? i want it like figma design make it like that

**Comment by Mayanksaininh** [comment]
I will provide u figma two days after tomorrow
