### ISSUE TITLE
Implement Station services

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#203]
# ✨ Feature Request

### **Description of the Feature**
I want to implement the station services backend and frontend

![Screenshot 2024-10-12 000127](https://github.com/user-attachments/assets/7aae5c93-3f2f-44b5-801d-d04074aeebcb)

### **Problem Statement**
A user entering station and date should see the available coolies , wheelchairs and cloakroom and can book the services accordingly and gets a notification for the booking.

### **Proposed Solution**
I will add backend controllers for fetching coolies , cloakroom and wheelchairs for specific stations and then integrate with the frontend to be able to book by a user.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
frontend is good you can implement but how will you implement tell me that

**Comment by haseebzaki-07** [comment]
@dhairyagothi we need to create controllers for fetching coolies , wheelchairs and cloakroom referenced to the station id, so we need to implement relationship in the schema. After fetching all the three booking stuffs we can proceed to book them further for the desired station by filling up the fields in the frontend and sending the data along to the backend to proceed with the booking.

After successful booking the user gets a notification along with the booking info.

**Comment by dhairyagothi** [comment]
> @dhairyagothi we need to create controllers for fetching coolies , wheelchairs and cloakroom referenced to the station id, so we need to implement relationship in the schema. After fetching all the three booking stuffs we can proceed to book them further for the desired station by filling up the fields in the frontend and sending the data along to the backend to proceed with the booking.
> 
> After successful booking the user gets a notification along with the booking info.

make changes i will see

**Comment by haseebzaki-07** [comment]
@dhairyagothi sure I am on it
