### ISSUE TITLE
Add "Already have an account Login" in signUp page and visa versa

### ISSUE THREAD

**Issue by shivamy009** [Mehtarishita/StationGuide#21]
![Screenshot 2024-10-01 222040](https://github.com/user-attachments/assets/0f689d6f-5078-41c3-982e-bb2d6f539390)
![Screenshot 2024-10-01 222251](https://github.com/user-attachments/assets/0a7dc8a4-fb90-4e29-878b-6ed245081542)
Add feature if user have already account and add if user not have account

**Comment by shivamy009** [comment]
Please assign me to fix issue

**Comment by dhairyagothi** [comment]
someone has already make a pr regarding this 
check #30
