### ISSUE TITLE
Add Scroll to top button

### ISSUE THREAD

**Issue by SurajPrakash24** [Mehtarishita/StationGuide#211]
# ✨ Feature Request

### **Description of the Feature**
I want to add Scroll to top button as it helps users not to scroll whole page to go back to top of the page. This button will we mostly needed for some pages such as contributors page. I have added button details in Proposed Solution part.

@dhairyagothi  Plz review and accept the PR under gssoc-ext level 2 and hacktoberfest.

### **Problem Statement**
It will be very efficient for user to directly go to top of page with just one click. 

### **Proposed Solution**
-Implement a "Scroll to Top" button that appears when the user scrolls down more than 200 pixels.
-Button should smoothly scroll the page back to the top when clicked.
-To add responsive styling for better user experience

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
add it asap  @SurajPrakash24

**Comment by SurajPrakash24** [comment]
@dhairyagothi I have created a PR for this issue. Plz review and merge it under gssoc-ext level 2 and hacktoberfest-accepted.
