### ISSUE TITLE
As your stats section is not looking.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Mehtarishita/StationGuide#212]
# ✨ Feature Request

### **Description of the Feature**
Stats section is not looking good in UI

### **Proposed Solution**
I will make it good looking UI and also use react countup library in it.

### **Additional Context**
![statsagain](https://github.com/user-attachments/assets/34232655-ec2a-4a61-babd-b31b6b03b423)

https://github.com/user-attachments/assets/bbfebeac-97e6-4b83-aab5-49d65c4bd028

### **Are you participating in GSSoC?**
- [1 ] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
assigned @VinayLodhi1712
