### ISSUE TITLE
Add footer in the application

### ISSUE THREAD

**Issue by SurajPrakash24** [Mehtarishita/StationGuide#213]
# 🖥️ Frontend Issue

### **Description**
I want to add footer to the application with some useful details and links to easily navigate between different pages. There is no footer to the home page, login page and signup page.

@dhairyagothi  Plz assign this issue to me under gssoc-ext level 2 or 3 and hacktoberfest.

### **Expected behavior**
 These page will have a footer with good UI and useful links and details. The footer will also be responsive for different device widths.

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
no need of footer check figma design
