### ISSUE TITLE
Design and contact page

### ISSUE THREAD

**Issue by Mahy-31** [Mehtarishita/StationGuide#217]
The UI layout of the about us page is looking very simple. I believe with my UI/UX design experience, I will create an attractive about us page. And There's no separate contact us page.
I would like to create that as well. Could you please assign this issue to me?

**Comment by dhairyagothi** [comment]
contact page is already there you can enhance it more

**Comment by Mahy-31** [comment]
> contact page is already there you can enhance it more

@dhairyagothi Can I enhance both about us and contact us page?

**Comment by dhairyagothi** [comment]
> > contact page is already there you can enhance it more
> 
> @dhairyagothi Can I enhance both about us and contact us page?

do in two different issues

**Comment by Mahy-31** [comment]
> > > contact page is already there you can enhance it more
> > 
> > 
> > @dhairyagothi Can I enhance both about us and contact us page?
> 
> do in two different issues

okey sir

**Comment by dhairyagothi** [comment]
> > > > contact page is already there you can enhance it more
> > > 
> > > 
> > > @dhairyagothi Can I enhance both about us and contact us page?
> > 
> > 
> > do in two different issues
> 
> okey sir

areee i am not sir 😆
