### ISSUE TITLE
Enhancement of About Us page

### ISSUE THREAD

**Issue by Mahy-31** [Mehtarishita/StationGuide#221]
The about us page looks simple. I believe with my web designing experience, I can make it look more attractive. Could you assign me this task please?

**Comment by akilesh26** [comment]
Hi, I would like to work on this issue. Please assign me the same.

**Comment by dhairyagothi** [comment]
@akilesh26 assigned

**Comment by anchalchaturvedi08** [comment]
hello, I want to work on this issue. please assign it to me.
