### ISSUE TITLE
Station Code with Station Name 

### ISSUE THREAD

**Issue by the-matrixneo** [Mehtarishita/StationGuide#223]
# ✨ Feature Request

### adding station code with station name
1. A clear and concise description of the feature or enhancement you want to propose. --> I want to add station code with station name . If the user only types the station code under " search for railway station" it will be easily be shortlisted . The user of station sarthi only has to type station code .
. I also want to add some station .  
EXAMPLE : new Delhi railway station : - NDLS , Patna Railway Station : PNBE

2. Station Code not mentioned 
 Since the station code is not mentioned , it is the first entry on the railway station list , accompanied by corresponding station name.

3.Adding the station Code
 Picture attached below . 

4. Added Screenshot
<!-- Add any other context, screenshots, or information related to the feature request here. - 
![Station code Edit](https://github.com/user-attachments/assets/c67d5e19-d2d3-4fca-8f1d-292d1a46bf4d)
5. Are you participating in GSSoC?**
- Yes
6. Assign me this issue under ▶️ hacktoberfest , Gssoc ext'24 , i would like to work on it.😊

**Comment by the-matrixneo** [comment]
![Station code Edit](https://github.com/user-attachments/assets/3da82818-5545-4bb8-a5b2-5a6b839209a5)

**Comment by dhairyagothi** [comment]
okay change json file

**Comment by the-matrixneo** [comment]
**Want to confirm**
@dhairyagothi sir , 
frontend/src/Pages/stations.jsx <- the file is under this path 
is that json or jsx?

**Comment by dhairyagothi** [comment]
> **Want to confirm** @dhairyagothi sir , frontend/src/Pages/stations.jsx <- the file is under this path is that json or jsx?

`jsx`

**Comment by the-matrixneo** [comment]
@dhairyagothi sir pls add the correct label of hactoberfest and level1

**Comment by dhairyagothi** [comment]
> @dhairyagothi sir pls add the correct label of hactoberfest and level1

already added

**Comment by the-matrixneo** [comment]
@dhairyagothi sir if I am not wrong , 
Hacktoberfest label as specified by Programme Manager should be "hacktoberfest"

**Comment by dhairyagothi** [comment]
> @dhairyagothi sir if I am not wrong , Hacktoberfest label as specified by Programme Manager should be "hacktoberfest"

updated thankyou for informing

**Comment by harjasae2001** [comment]
can u pls assign me this issue ??
