### ISSUE TITLE
[feat] : Improving frontend/src/Pages/Register.jsx file with some changes

### ISSUE THREAD

**Issue by Yash-Vashishth** [Mehtarishita/StationGuide#225]
# 🖥️ Frontend Issue

Hi @dhairyagothi !! I saw your code and I saw this file requires a few changes for smoother functioning and adding components. This is an issue that is raised in frontend/src/Pages/Register.jsx . 
1. **Component Decomposition**: Created a reusable FormInput component for input 
      fields.
3. **Consistent Naming Conventions**: Used formData object to handle form state.
4. **Improved Error Handling**: Enhanced error messages for registration failures.
5. **Enhanced UX/UI**: Added loading indicators and password strength feedback.
6. **Memoization**: Memoized FormInput component for improved performance.

### Are you participating in GSSoC?
- [.] Yes
- [] No

**Comment by Yash-Vashishth** [comment]
PLease add gssoc-ext, hacktoberfest and level 2 tag to this issue

Thanks,
Yash Vashishth
(Contributor, GSSoC'24 and Hacktoberfest)

**Comment by dhairyagothi** [comment]
i will check PR if found lot of changes and work i will update level
