### ISSUE TITLE
Add details of train that goes by the station

### ISSUE THREAD

**Issue by divyalakshmi0** [Mehtarishita/StationGuide#226]
# ✨ Feature Request
![image](https://github.com/user-attachments/assets/461fe215-a071-4d7e-85ff-05974340ef03)

When the station is clicked it only shows the station names

![image](https://github.com/user-attachments/assets/dd2d2fd1-96c0-4785-bc86-61acda7cdc2e)

But if it displays the details of the trains that go by this station means it would be more useful for the user pov!!!!!!

### Solution
To add details of the trains that going to cross by this station when the station is searched like a pop up, instead just adding to favourites.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
@divyalakshmi0 check figma design and idea of project we want to add station details here . if you can then tell me
