### ISSUE TITLE
Confirm Bookings

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#233]
# ✨ Feature Request

### **Description of the Feature**
I want to add frontend and backend for booking confirmation via tha bookings page.

### **Problem Statement**
A user clicking on the "Book Now" button for services after selecting a particular station should see a dropdown form for filling in the details like timing/type of service/departure/platform number etc... . After filling the details for specific sevice like: cloakroom, coolie or wheelchair should get a confirmation/notification from the backend for the same booking.

### **Proposed Solution**
I will create new forms for taking input of these bookings in the same component shown below and then integrate it with the backend for realtime bookings that gets saved in the database and notifications.

![Screenshot 2024-10-13 131751](https://github.com/user-attachments/assets/c4cba718-7b3c-4ac6-b9b5-6b0261c81544)

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
some backend is already there

**Comment by haseebzaki-07** [comment]
@dhairyagothi yeah I will merge it!
