### ISSUE TITLE
Adding input validations

### ISSUE THREAD

**Issue by Gauravtb2253** [Mehtarishita/StationGuide#235]
# ✨ Feature Request

### **Description of the Feature**
Hello I would like to add proper input form validation for the login and signup page
Pls assign this to me

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
how you will do this backend is already setup not working on hosting

**Comment by Gauravtb2253** [comment]
> how you will do this backend is already setup not working on hosting

I will client side input form validations with proper error messages displaying
