### ISSUE TITLE
Improve alignment of elements

### ISSUE THREAD

**Issue by manikdamle** [Mehtarishita/StationGuide#242]
# 🖥️ Frontend Issue

### **Description**
Elements on the page are not well aligned

### **Steps to Reproduce**

1. Go to StationGuide website
2. Scroll down
3. See error at bottom right corner

### **Expected behavior**

The elements should be well aligned with equal spacing

### **Actual behavior**

The elements are not aligned

### **Screenshots or Video**

![align](https://github.com/user-attachments/assets/633ba53c-762c-4b5d-84e7-c7a4167e5550)

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by manikdamle** [comment]
@dhairyagothi pls assign this issue to me

**Comment by dhairyagothi** [comment]
@manikdamle start working will update level according to changes you have made

**Comment by manikdamle** [comment]
Ok!

**Comment by manikdamle** [comment]
Something is wrong with the code ig! 
The root component is empty on index.htm.
When run locally most of the visible screen is white.
@dhairyagothi Pls check.
![Screenshot (154)](https://github.com/user-attachments/assets/60d4b822-b770-4094-ae48-ac8295659c19)

**Comment by dhairyagothi** [comment]
@manikdamle its a react project you cannnot run it directly you have to install npm first

**Comment by manikdamle** [comment]
Ok
