### ISSUE TITLE
google language change dropdown menu

### ISSUE THREAD

**Issue by shriyadindi** [Mehtarishita/StationGuide#244]
# 🖥️ Frontend Issue

### **Description**

I would like to work on the language change dropdown and enhance the design and alignment of the bar.

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### Are you participating in GSSoC?
- [ ] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
this is duplicate issue 
comment on #114 i will assign you there
