### ISSUE TITLE
Add User Profile Section 

### ISSUE THREAD

**Issue by synthiaekka** [Mehtarishita/StationGuide#247]
# ✨ Feature Request
It will allow users to add a profile picture, Edit Profile, Logout, or View Profile under the profile section, enhancing personalization.

It will enhance the user profile section by allowing users to upload profile pictures and access quick actions such as 'Edit Profile', 'Logout', and 'View Profile' for improved personalization and ease of navigation.

![issue4](https://github.com/user-attachments/assets/93cd48c8-0294-4a63-bf32-8f2bad8003cd)

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
ok good issue go ahead make one PR at a time don't add multiple PR as you have assigned more than one issues . 
GOOD lUCK

**Comment by synthiaekka** [comment]
Okay. Thank you

**Comment by srishti023** [comment]
Please assign me this issue

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi should I take this issue!
