### ISSUE TITLE
Dark Mode Toggle

### ISSUE THREAD

**Issue by synthiaekka** [Mehtarishita/StationGuide#248]
# ✨ Feature Request

I will implement a dark mode toggle within the sidebar, allowing users to seamlessly switch between light and dark modes for a personalized and visually adaptive user experience."

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
go for it @synthiaekka 
you will add toggle only or complete dark mode ??

**Comment by synthiaekka** [comment]
Only toggle. Also could you please add the label "Level" for this issue?

**Comment by dhairyagothi** [comment]
> Only toggle. Also could you please add the label "Level" for this issue?

for toggle level 1

**Comment by jjf2009** [comment]
@dhairyagothi if this issue is open can i work on it
