### ISSUE TITLE
Add favourite Station

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#250]
# ✨ Feature Request

### **Description of the Feature**
Clicking on the star mark on the station card should add it to a new list of stations containing the favourites for the user.

### **Proposed Solution**
On clicking the star should send data of the station to the backend to associate with the user profile.
![Screenshot 2024-10-14 202138](https://github.com/user-attachments/assets/88ace096-1754-4560-bb77-c29f5c616f13)

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
code is already there just fix it

**Comment by haseebzaki-07** [comment]
@dhairyagothi sure

**Comment by haseebzaki-07** [comment]
@dhairyagothi The frontend part is ready should I implement it in the backend also? To actually keep the track of data in the database.

**Comment by haseebzaki-07** [comment]
@dhairyagothi please reply there is another issue to tackle.
