### ISSUE TITLE
To implement the Carousel instead of normal bg image 

### ISSUE THREAD

**Issue by sheetal-81** [Mehtarishita/StationGuide#251]
# ✨ Feature Request

### **Description of the Feature**

By adding carousel the page will look more dynamic and interactive 

### **Problem Statement**

since the page looks simple i want to add this carousel feature so it will look good 

### **Proposed Solution**

i will add four pages in terms of carousel and with some time spans then after time interval image will change automatically

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
its a nice idea good @sheetal-81 

but add in similar way like full size background image and that whitish bottom . you please check FIGMA UI in files .. and make it responsive too
