### ISSUE TITLE
Registration failing

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#252]
# 🐞 Bug Report

### **Describe the bug**
Even after filling the desired fields the user registeration is failing and the cause is unknown.

### **Steps to Reproduce**
1. Go to /Register
2. Click on Register after filling all the fields 
3. See error

### **Expected behavior**
Ideally the user should get registered with a successful message or the user should know the reason for failure

### **Actual behavior**
A error is shown on the top

### **Screenshots or Video**
![Screenshot 2024-10-14 202957](https://github.com/user-attachments/assets/b8e1d854-fb77-4c9f-8d3c-6dcd8be2a772)

### **Environment**
Please provide the following details:
- **OS**: _e.g., iOS, Windows, Linux, macOS_
- **Browser/Software**: _e.g., Chrome, Firefox, Node.js_
- **Version**: _e.g., 22.0_

**Comment by dhairyagothi** [comment]
have you check backend ??
hosted link is only in frontend

**Comment by haseebzaki-07** [comment]
@dhairyagothi Well I'll Check

**Comment by haseebzaki-07** [comment]
@dhairyagothi The login form in the backend displays successful login even after entering any random texts in the fields, without authenticating the user and the signup component do not even receives inputs in the input fields. So there is a lot to fix.
