### ISSUE TITLE
Travel Alert

### ISSUE THREAD

**Issue by 23wh1a0513** [Mehtarishita/StationGuide#254]
# ✨ Feature Request

### **Description of the Feature**

Travel Alert

### **Problem Statement**

Adding Travel Alert to this could significantly enhance the user experience by helping passengers manage their journeys more efficiently.

### **Proposed Solution**

Incorporating these reminders can make this a more comprehensive travel assistant, helping passengers navigate their journeys smoothly and efficiently.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by 23wh1a0513** [comment]
@dhairyagothi assign me the work.

**Comment by dhairyagothi** [comment]
hey @23wh1a0513 thankyou for raising issue please tell me what type of alerts you want to add ??
and project is in react so you have to work accordingly 
also please check figma UI before starting 
please tell more about issue

**Comment by 23wh1a0513** [comment]
https://github.com/user-attachments/assets/5e3d716b-cc9f-4b09-a6e7-a78a66e540e0

Here is a demo

**Comment by dhairyagothi** [comment]
but how you apply this file is in react

**Comment by 23wh1a0513** [comment]
Should the share the html css js code
