### ISSUE TITLE
Misalignment in footer

### ISSUE THREAD

**Issue by Bhum-ika** [Mehtarishita/StationGuide#256]
# 🐞 Bug Report

### **Describe the bug**
Contributors' button is not aligned, whether u r placing at footer or sidebar, also it should look different from others

### **Expected behavior**
It should look unique and well aligned

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/3f63c42d-69ef-4812-917c-f34bc6e49307)

### **Environment**
Please provide the following details:
- **OS**: _e.g., iOS, Windows, Linux, macOS_
- **Browser/Software**: _e.g., Chrome, Firefox, Node.js_
- **Version**: _e.g., 22.0_

**Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.**

**Comment by dhairyagothi** [comment]
assignedd @Bhum-ika please check in responsivness also go ahead . you can connect if you need any help

**Comment by Bhum-ika** [comment]
Sure, thanks

**Comment by Bhum-ika** [comment]
Hi, could you please add level 2? 
I would really appreciate it
