### ISSUE TITLE
Title : Adding backicon in all pages  

### ISSUE THREAD

**Issue by RiddhiM170904** [Mehtarishita/StationGuide#262]
# 🖥️ Frontend Issue

### **Description**
I will check and back icon in all pages using proper routes and fix pre existing back icons

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### Are you participating in GSSoC?
- [X ] Yes
- [ ] No

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
