### ISSUE TITLE
Redirecting after Login

### ISSUE THREAD

**Issue by Gauravtb2253** [Mehtarishita/StationGuide#265]
# ✨ Feature Request

### **Description of the Feature**
I would like to add redirecting feature when the user logins

### **Problem Statement**
Currently the page is not changing after user login

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by Gauravtb2253** [comment]
any updates

**Comment by dhairyagothi** [comment]
what type of redirect ?

**Comment by Gauravtb2253** [comment]
once the login is successful a new page should be shown to the user currently its not happening

**Comment by Gauravtb2253** [comment]
any updates
