### ISSUE TITLE
Add Intro for website

### ISSUE THREAD

**Issue by AnushkaS77** [Mehtarishita/StationGuide#266]
# ✨ Feature Request

### **Description of the Feature**
just as netflix, i want like to add an intro animated video before the home page appears for making it look more creative.

### **Proposed Solution**
ive worked on this feature with past projects as well, one example is given below
[AgroTech AI.webm](https://github.com/user-attachments/assets/76d94795-a8ec-46e1-8b46-eb372af022b9)

### **Are you participating in GSSoC?**
- Yes

please assign me, and add the gssoc-ext, hackotober , level tag as well , thankyou

**Comment by dhairyagothi** [comment]
@AnushkaS77  it is known as preloader there is a issue for that check figma ui just want white bg and logo and text 
assigning you make PR asap
