### ISSUE TITLE
fix cursor issue and overlapping icons 

### ISSUE THREAD

**Issue by ishicodz** [Mehtarishita/StationGuide#268]
# 🖥️ Frontend Issue

-fixing the overlapping icons on home page 
-fixing the cursor issue
for better user experience

<img width="383" alt="Screenshot 2024-10-15 212025" src="https://github.com/user-attachments/assets/6444f8fb-cc7f-4d04-b8c0-b3674a564114">
<img width="329" alt="Screenshot 2024-10-15 212150" src="https://github.com/user-attachments/assets/d43d6a90-12d5-4832-bb6b-43cacf0aeb60">

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

@dhairyagothi  can you please assign this issue to me under the gssoc-ext, hacktoberfest-accepted and level label?

**Comment by dhairyagothi** [comment]
make it for responsivness @ishicodz
