### ISSUE TITLE
Want to improve the look of the website

### ISSUE THREAD

**Issue by Dipanita45** [Mehtarishita/StationGuide#271]
# ✨ Feature Request

### **Description of the Feature**
<-- Add or update  the css properties -->

### **Problem Statement**
<-- To make it user friendly to the user-->

### **Proposed Solution**
<Use more colour constrast, transition,.. etc

### **Are you participating in GSSoC?**
- [+] Yes
- [ ] No

Please assign me to the issue 
Thank you

**Comment by dhairyagothi** [comment]
what type of look you want to change ?? @Dipanita45

**Comment by Dipanita45** [comment]
Home page
