### ISSUE TITLE
the language select section or button is not placed properly.

### ISSUE THREAD

**Issue by Sandigupta** [Mehtarishita/StationGuide#272]
# 🖥️ Frontend Issue

### **Steps to Reproduce**

Fix this problem so that the site's user interface is better.

### **Screenshots or Video**

![Screenshot 2024-10-16 112731](https://github.com/user-attachments/assets/81fe0528-d038-4c80-b768-6d8347a1ae4f)

### Are you participating in GSSoC?
- [x] Yes
[ ] No

**Comment by dhairyagothi** [comment]
@Sandigupta change it with a svg icon on tapping icon languages will be available

**Comment by Sandigupta** [comment]
@dhairyagothi Please Can you explain it more? I am not able to get it.
thanks

**Comment by srishti023** [comment]
Please assign me this issue I will do it and can change it with a svg icons on tapping languages ✅
