### ISSUE TITLE
Add a show password button

### ISSUE THREAD

**Issue by devarsheecodess** [Mehtarishita/StationGuide#273]
# 🐞 Bug Report

### **Describe the bug**
Login and signup page lacks show password button

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/5fd71d8f-7cf5-459f-8207-fdeadb74b8c2)
![image](https://github.com/user-attachments/assets/16a4d4cc-f9c6-4088-8556-a2779edc6b6f)

@dhairyagothi assign me this issue under gssoc-ext, hacktoberfest-accepted and level2

**Comment by dhairyagothi** [comment]
added by PR #264
