### ISSUE TITLE
I want to add icons in login and register page.

### ISSUE THREAD

**Issue by Adityadhiman0** [Mehtarishita/StationGuide#274]
# ✨ Feature Request

### **Description of the Feature**
If there are  icons before labels in login and register page then it will enhance the use interface.

### **Problem Statement**
I have attached a screenshot where i want to add icons.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No
![Screenshot 2024-10-16 173810](https://github.com/user-attachments/assets/001ad8e1-79fd-4acd-970e-8ff471fbfca5)

**Comment by Adityadhiman0** [comment]
Please assign the issue to me I will resolve it today.

**Comment by dhairyagothi** [comment]
approved assigned @Adityadhiman0

**Comment by RiddhiM170904** [comment]
Please assign this issue to me @dhairyagothi

**Comment by dhairyagothi** [comment]
go for it @RiddhiM170904
