### ISSUE TITLE
Bug : Registration page is not accepting any value from user. 

### ISSUE THREAD

**Issue by Adityadhiman0** [Mehtarishita/StationGuide#275]
# 🐞 Bug Report

### **Describe the bug**
Input fields are not accepting any value.
When user type their name or password in registration form, form is not accepting it.

### **Steps to Reproduce**
1. Go to 'registration page'
2. Try to 'type name '
3. See error

### **Expected behavior**
Registration form should work properly.

### **Actual behavior**
Registration form is not accepting any value.

### **Screenshots or Video**

https://github.com/user-attachments/assets/1fa0a1e2-facc-48fa-88aa-1ea12062479a

### **Environment**
Please provide the following details:
- **OS**: _e.g., Windows
- **Browser/Software**: _e.g., Chrome
- **Version**: _e.g., 22.0_

**Comment by Adityadhiman0** [comment]
Please assign this issue to me.

**Comment by dhairyagothi** [comment]
![image](https://github.com/user-attachments/assets/d0821dff-f6bc-456d-b3fb-dd3d207e83df)

working for me
