### ISSUE TITLE
Improve Select Language Box UI

### ISSUE THREAD

**Issue by Rahilsamani** [Mehtarishita/StationGuide#277]
# 🖥️ Frontend Issue

### **Description**
The current user interface for the select language box is not visually appealing and can be confusing for users. It lacks proper styling and does not provide a good user experience.

### **Steps to Reproduce**

1. Go to the main page of the application.
2. Click on the language selection dropdown.
3. Observe the current UI design.

### **Expected behavior**
The select language box should have a modern design with proper alignments, and clearly display available languages.

### **Screenshots or Video**
<img width="305" alt="image" src="https://github.com/user-attachments/assets/8350056e-6ab2-4f5e-8ec4-a19cb8fc5f6a">

### Are you participating in GSSoC?
Yes

**Comment by sayiamarora** [comment]
Hey @dhairyagothi Could you assign me this issue. So that I could increase better user experience of this website.

**Comment by dhairyagothi** [comment]
its a duplicate issue
