### ISSUE TITLE
 Center Booking Page Content

### ISSUE THREAD

**Issue by Rahilsamani** [Mehtarishita/StationGuide#278]
# 🖥️ Frontend Issue

### **Description**
The content on the booking page is currently aligned to the top, making it appear unbalanced. Centering the content would improve the overall layout and user experience.

### **Steps to Reproduce**

1. Navigate to the booking page.
2. Observe the placement of the content.
3. Note that the content is sticking to the top of the page.

### **Expected behavior**
The content on the booking page should be centered vertically, providing a more visually appealing layout.

### **Actual behavior**
The booking page content is aligned at the top, which makes the page look unbalanced and less user-friendly.

### **Screenshots or Video**
<img width="950" alt="image" src="https://github.com/user-attachments/assets/f881b965-6081-4fbe-be51-ee3171358c81">

### Are you participating in GSSoC?
Yes

**Comment by dhairyagothi** [comment]
Na previous one UI is best if you can change something more in that only then tell
