### ISSUE TITLE
 Issue with Icon Visibility in User Interface

### ISSUE THREAD

**Issue by TornovDutta** [Mehtarishita/StationGuide#28]
# 🖥️ Frontend Issue

### **Description**

 The icons for services like Navigation, Booking, Station, and others are not displayed properly. The labels are visible, but the icons appear misaligned or partially obscured. This could be due to improper scaling, transparency issues, or CSS errors. Adjusting the layout or correcting the styling may resolve the problem.

### **Screenshots or Video**

![Screenshot 2024-10-01 230515](https://github.com/user-attachments/assets/665512ab-b84b-4493-b186-51999570c591)

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by TornovDutta** [comment]
i want to work on it. please assign it to me.
@Premkolte

**Comment by TornovDutta** [comment]
please lebal the issuse.
@Premkolte

**Comment by Premkolte** [comment]
I'll ask @dhairyagothi to assign it to you.

**Comment by dhairyagothi** [comment]
assigned @TornovDutta

**Comment by dhairyagothi** [comment]
make all icons and text aligned proper as UI 
check https://github.com/dhairyagothi/StationGuide/blob/34f1aff5ebdddf226eff342fbc0e87895fce497b/StationGuideFigma.md

make as it is asap

**Comment by TornovDutta** [comment]
The project is not cloning to VS code.

![Screenshot 2024-10-02 174308](https://github.com/user-attachments/assets/e54b9076-fdc1-484d-8bf7-e6f4343f6424)
Please help me  , @dhairyagothi

**Comment by dhairyagothi** [comment]
Do you use GitHub desktop ??

Clone using GitHub desktop....

And use personal net please


> The project is not cloning to VS code.
> 
> ![Screenshot 2024-10-02 174308](https://github.com/user-attachments/assets/e54b9076-fdc1-484d-8bf7-e6f4343f6424)
> Please help me  , @dhairyagothi

**Comment by TornovDutta** [comment]
Sorry, I cannot work on it. Could you please pass it to another contributor.
@dhairyagothi

**Comment by dhairyagothi** [comment]
Sure thank you for your confirmation

**Comment by rebornstar1** [comment]
I want to work on this issue

**Comment by dhairyagothi** [comment]
> I want to work on this issue

Assigning @rebornstar1  make PR asap
