### ISSUE TITLE
adding back to home button to the contributors page

### ISSUE THREAD

**Issue by trahulprabhu38** [Mehtarishita/StationGuide#281]
@dhairyagothi i can add back to home button to the contributors page. can you please assign me this issue,

<img width="736" alt="Screenshot 2024-10-17 at 7 40 54 PM" src="https://github.com/user-attachments/assets/49468c6a-85fe-4768-9e63-991bacc50734">

**Comment by dhairyagothi** [comment]
It's already there bro @T-Rahul-prabhu-38

**Comment by dhairyagothi** [comment]
It's already there bro @T-Rahul-prabhu-38

**Comment by dhairyagothi** [comment]
It's already there bro @T-Rahul-prabhu-38

**Comment by dhairyagothi** [comment]
Let me show
