### ISSUE TITLE
FEAT: I want to add password strength indicator in registration page.

### ISSUE THREAD

**Issue by Adityadhiman0** [Mehtarishita/StationGuide#283]
# ✨ Feature Request

### **Description of the Feature**
This feature will help the user to know that how strong there password is.

### **Proposed Solution**
There will be a password strength indicator below the password input box.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
already there bro @Adityadhiman0

**Comment by Adityadhiman0** [comment]
Then may I enhance it.
