### ISSUE TITLE
Adding description in about us Page

### ISSUE THREAD

**Issue by Ishika-Gupta06** [Mehtarishita/StationGuide#284]
It will conatin the detail info. about the StationGuide along with how to use it

**Comment by Ishika-Gupta06** [comment]
@dhairyagothi  PLEASE ASSIGN ME UNDER GSSOC-EXT, HACKTOBERFEST & LEVEL-1,2,3

**Comment by dhairyagothi** [comment]
Assigned @Ishika-Gupta06
