### ISSUE TITLE
✨ Add a Visit Counter for the Website ( Using API and Backend Technology )

### ISSUE THREAD

**Issue by SrijaVuppala295** [Mehtarishita/StationGuide#286]
# ✨ Feature Request

### **Description of the Feature**
I would like to propose adding a visit counter to the website page that tracks the number of visitors. This counter should dynamically increment each time a user visits the page and can be displayed prominently to provide real-time statistics.

### **Problem Statement**
Currently, there is no way to track or display the number of visitors to the website. This lack of visibility may hinder the ability to assess user engagement and popularity of specific pages. A visit counter would help users and administrators gauge interest and encourage more interactions.

### **Proposed Solution**
- **Dynamic Counter**: Implement a counter that increments with each page visit.
- **Storage**: Use a backend solution (like a database or a simple file) to store the current count, ensuring that it persists across sessions and server restarts.
- **Display**: The counter should be prominently displayed on the page, showing the number of visits in a user-friendly format, such as "This page has been visited 150 times!".
- **Reset Option**: Provide an option for admins to reset the counter if needed.

![image](https://github.com/user-attachments/assets/dcdb7f40-fc32-4d0f-9af7-1d59fefeefa6)

### **Alternatives Considered**
- **Tracking Tools**: Instead of a custom-built counter, consider using third-party analytics tools (like Google Analytics) to track visits. However, these tools may not provide real-time updates visible to users on the website.

### **Additional Context**
Adding a visit counter can increase user engagement by showcasing the popularity of the content. It also provides an interesting statistic that might encourage users to participate more, knowing they are part of a larger audience.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
no need for now bro i will assign it later
