### ISSUE TITLE
overlapping of scroll to top button in mobile breakpoints

### ISSUE THREAD

**Issue by AE-Hertz** [Mehtarishita/StationGuide#290]
# 🖥️ Frontend Issue

### **Description**
overlapping of scroll to top button in mobile breakpoints

### **Expected behavior**
should not overlap, 

### Are you participating in GSSoC?
- [X ] Yes
- [ ] No

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.
