### ISSUE TITLE
Update Booking Page

### ISSUE THREAD

**Issue by PraveenUppar** [Mehtarishita/StationGuide#291]
# 🖥️ Frontend Issue

### **Description**
Change existing UI/UX of the booking the elements are not aligned 

### **Steps to Reproduce**

1. Check Booking Page

### **Screenshots or Video**

![Screenshot 2024-10-18 123328](https://github.com/user-attachments/assets/ecba5ac7-251b-478a-b487-61273f7a16dd)

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi he seems to be inactive at the issue, can u assign me so that I can work, I will make the PR by tommorow
