### ISSUE TITLE
Add Settings Page

### ISSUE THREAD

**Issue by PraveenUppar** [Mehtarishita/StationGuide#303]
# ✨ Feature Request

### **Description of the Feature**
Add settings page to the station yarthi when user click settings in navbar it should redirect to settings page

### **Problem Statement**
There is no settings page

### **Proposed Solution**
Add a new settings page

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi he seems to be inactive at the issue, can u assign me so that I can work, I will make the PR by tommorow

**Comment by NK-Works** [comment]
@dhairyagothi its been two weeks with no response i can make it within a day can you assign me

**Comment by dhairyagothi** [comment]
Assigned @NK-Works @haseebzaki-07
