### ISSUE TITLE
Improving the navbar and Search feature

### ISSUE THREAD

**Issue by hritika2409** [Mehtarishita/StationGuide#31]
- # 🖥️ Frontend Issue

### **Expected behavior**

A proper Navbar should be there for easy understanding and working.The search option is even not working

### **Actual behavior**

-Search option not working .Poor navbar feature

### **Screenshots or Video**

https://github.com/user-attachments/assets/6fd072a7-13db-4c24-9c1e-7a3f35850f23

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Assigned @hritika2409 
Please update me in 24 hours with work

**Comment by hritika2409** [comment]
https://github.com/user-attachments/assets/073528ad-9d49-43fc-88fd-4ae0a298b7a9

Is this fine for you & can you please remove the search from the background image

**Comment by hritika2409** [comment]
if its fine @dhairyagothi for you then can i make a merge request?

**Comment by dhairyagothi** [comment]
Good to go @hritika2409 just remove behind one search icon

**Comment by dhairyagothi** [comment]
Also sync fork and pull origin before making PR @hritika2409

**Comment by hritika2409** [comment]
@dhairyagothi the background search icon is not a icon i guess it is the part of image but i will try

**Comment by dhairyagothi** [comment]
> @dhairyagothi the background search icon is not a icon i guess it is the part of image but i will try

Let it be for now i will do. I have merged PR don't make a new PR for same issue 

Good luck
