### ISSUE TITLE
Building a beautiful Login/Signup Page

### ISSUE THREAD

**Issue by Ashish-Patnaik** [Mehtarishita/StationGuide#311]
# ✨ Feature Request

### **Description of the Feature**
A visually appealing Login/Signup page

### **Problem Statement**
Make the website visually more attractive 

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by akilesh26** [comment]
Hi, I would like to work on this issue. Please assign me the same.
