### ISSUE TITLE
Adding google login on the login page

### ISSUE THREAD

**Issue by LitZeus** [Mehtarishita/StationGuide#316]
# 🐞 Bug Report

### **Describe the bug**
We do have the google login but on register page, we dont have any login facility on the login page

### **Steps to Reproduce**
1. Go to Login
2.  Scroll down the page
3.  You will not see the login button but you will see the same on the register page

### **Expected behavior**
The login page should have the login button, else we are using only half of the advantage of it

### **Actual behavior**
only the register page has the google login button

### **Screenshots or Video**
The login page

![image](https://github.com/user-attachments/assets/a27b92bf-bb87-43fe-a292-91956558996d)

<br />
The register page

![image](https://github.com/user-attachments/assets/f8b3f464-872f-4908-80b0-a11b1d395b69)

### **Environment**
Please provide the following details:
- **OS**:  Windows 11
- **Browser/Software**:  Edge
- **Version**: 129.0.2792.89 (Official build) (64-bit)

### **Logs & Error Messages**
n/a

**Comment by dhairyagothi** [comment]
already there @LitZeus
