### ISSUE TITLE
Enhancing the  custom404 exhisting Error page

### ISSUE THREAD

**Issue by sushil-sagar05** [Mehtarishita/StationGuide#320]
I see that there is not user friendly ui of 404 page that redirects when user types in a wrong URL. Kindly assign me to design custom error page for this website.

eg: 
![gssoc-7](https://github.com/user-attachments/assets/c5f33e4f-f43a-4e96-9d97-bc2e07376443)

**Comment by dhairyagothi** [comment]
@sushil-sagar05 make it according to theme Figma UI and a train image something like that i will change level after seeing changes in PR

**Comment by sushil-sagar05** [comment]
sure @dhairyagothi  i will give my best

**Comment by sushil-sagar05** [comment]
Hey @dhairyagothi  here is the design of error page .. Kindly See and review it and tell me what possible changes i make on this if possible
![stationsarthi-issue-08](https://github.com/user-attachments/assets/d8af0dab-0865-4515-9eac-f58f887afb21)

**Comment by dhairyagothi** [comment]
good change red colour of `on wrong track` to blue
