### ISSUE TITLE
Implementing forgot password on login page.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Mehtarishita/StationGuide#325]
# ✨ Feature Request

### **Description of the Feature**
Implementing forgot password feature on your website.

### **Problem Statement**
Forgot password feature implementing.

### **Proposed Solution**
implementing forgot password feature by sending mail otp to the user email and then check that otp is match with the input otp if match then enter new password and confirm the password and store new hashed password in database.

### **Are you participating in GSSoC?**
- [ 1] Yes
- [ ] No

**Comment by VinayLodhi1712** [comment]
can u plz @dhairyagothi sir add level in it. It will help me to grow in gssoc leaderboard. I am started working on it.

**Comment by dhairyagothi** [comment]
> can u plz @dhairyagothi sir add level in it. It will help me to grow in gssoc leaderboard. I am started working on it.

make PR i will give level according to changes you made and your work

**Comment by VinayLodhi1712** [comment]
@dhairyagothi can i get your .env.sample file because there is some issue i am not able to run backend.

**Comment by VinayLodhi1712** [comment]
@dhairyagothi sir does your registering functionality has some issue because i am not able to work on it because of that i am not able to work on the forgot password functionality.
