### ISSUE TITLE
Booking page overlapped with the language selection component.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Mehtarishita/StationGuide#326]
# 🖥️ Frontend Issue

### **Description**
Booking page overlapped with the language selection component.

### **Steps to Reproduce**
Go to the booking page.

### **Expected behavior**
Clear view of the booking page

### **Actual behavior**

Overlapping on the booking page

### **Screenshots or Video**
![booking](https://github.com/user-attachments/assets/23b1c388-8321-4155-8082-62b9b661d759)

### Are you participating in GSSoC?
- [ 1] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
what's your screen size bro ??

![Uploading Screenshot 2024-10-19 121037.png…]()

**Comment by VinayLodhi1712** [comment]
i have computer means full mode you can say. this is full page screenshot.
![booking2](https://github.com/user-attachments/assets/dc241100-fd45-49c7-9acb-16c74016ce62)

I will make it good look on full mode and responsive mode and there is no overlapping in it.
