### ISSUE TITLE
Chat bot is not opening in mobile screen

### ISSUE THREAD

**Issue by Suvadip-sana** [Mehtarishita/StationGuide#332]
# 🐞 Bug Report

### **Describe the bug**

In mobile screen the chat bot section is not opening properly as you seen on the screen recording. 
Need to fix it. 

### **Expected behavior**

It should be open properly in mobile screen as in computer screen

### **Screenshots or Video**

https://github.com/user-attachments/assets/04eb1c77-b2fb-4f03-98e7-bfd06174a7da

Please assign me this task. I want to work on it. 
If you assign me then add all the labels under gssoc-extd

**Comment by govindumeesala** [comment]
@dhairyagothi can I work on it
