### ISSUE TITLE
Custom 404 Page for Unmatched URLS

### ISSUE THREAD

**Issue by Surya-V-28** [Mehtarishita/StationGuide#334]
# ✨ Feature Request

Description:
Add a user-friendly 404 page that displays when users navigate to non-existent routes. The page should include a "Back to Home" button for easy navigation back to the homepage.

Currently 
![image](https://github.com/user-attachments/assets/30e47a97-8806-4fad-b951-6bd1f60f4751)

After the completing 
![image](https://github.com/user-attachments/assets/cf06b1d9-3af9-4e93-b61a-6adfb440c7da)

somthing similar 
Reason:
Enhances user experience by providing a clear path when users encounter broken links or mistyped URLs.

Request:
I'd like to work on this feature. Please assign it to me. under GSSoc and october fest
@dhairyagothi 

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No
- [x] hacktoberfest participants

**Comment by dhairyagothi** [comment]
duplicate issue of #320
