### ISSUE TITLE
Integrating the login/signup api with frontend.

### ISSUE THREAD

**Issue by tarunkumar2005** [Mehtarishita/StationGuide#34]
# 🖥️ Frontend Issue

### **Description**
I saw that on front end the login/signup is not working so i want to integrate the login/signup on frontend with the backend. By this the login/signup will be properly working and users will be able to login, signup and logout.

### **Steps to Reproduce**
I will use react and redux for this.

### **Expected behavior**
I want that users will be able to properly login and signup.

### **Actual behavior**
Login/Signup pages are not working and not integrated with the backend.

### Are you participating in GSSoC?
- [X ] Yes
- [ ] No

In hacktoberfest also

Assign this issue to me @dhairyagothi

**Comment by dhairyagothi** [comment]
Sure please Add @tarunkumar2005 
i will change badge according to PR 
go ahead

**Comment by tarunkumar2005** [comment]
@dhairyagothi Create the pull request you can check it and merge it.
