### ISSUE TITLE
Fixing the Mouse pointer

### ISSUE THREAD

**Issue by Swati-in** [Mehtarishita/StationGuide#340]
# 🐞 Bug Report
The mouse Pointer is not in right place.

### **Describe the bug**
The mouse pointer is sometimes working and sometimes not and it is not in the place of the mouse sometimes its up sometimes its down

### **Steps to Reproduce**
Just opened the link of the project and you can see the mouse pointer being bugged.

### **Expected behavior**
The customize mouse pointer should follow the mouse pointer.

### **Actual behavior**
The mouse pointer is sometimes working and sometimes not and it is not in the place of the mouse sometimes its up sometimes its down

### **Screenshots or Video**
my mouse was low 
![image](https://github.com/user-attachments/assets/39f14d14-195c-4ea0-bcd2-3931daa658f7)
![WhatsApp Image 2024-10-20 at 16 55 56_f92c2249](https://github.com/user-attachments/assets/404a44c5-a3fc-4971-84a2-e8d24dfe2aa8)

Checklist:-
- [x] I agree to follow this project's Code of Conduct
- [x] I have checked the existing issues
- [x] I'm a GSSOC'24 contributor and Hacktoberfest
- [x] I want to work on this issue
- [x] I have attached the Screenshort regarding my issue

### **Environment**
Please provide the following details:
- **OS**:Windows
- **Browser/Software**: Chrome,Brave
- **Version**: _e.g., 22.0_

**Comment by dhairyagothi** [comment]
yes that is a problem
