### ISSUE TITLE
Enhancing Booking Page

### ISSUE THREAD

**Issue by Bhum-ika** [Mehtarishita/StationGuide#341]
# 🖥️ Frontend Issue

### **Description**
The booking page needs some styling.

### **Steps to Reproduce**

1. Go to Footer
2. Click on Bookings

Kindly assign this issue to me 

### **Expected behavior**
Its should be appealing and attractive aligning with website theme

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/d8baa250-5373-4473-ad07-0d03a629f3b4)

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
make it responsive also @Bhum-ika
