### ISSUE TITLE
Enhancing Notifications Page

### ISSUE THREAD

**Issue by Bhum-ika** [Mehtarishita/StationGuide#343]
# 🖥️ Frontend Issue

### **Description**
The Notification page needs standard , better and minimalistic styling

### **Expected behavior**
It should look minimal and appealing

### **Actual behavior**
It is quite plain, have no hover effect and title width is not defined due to which date is not written in one line

### **Screenshots or Video**

![image](https://github.com/user-attachments/assets/885cf3d2-6bdf-4125-a79e-7decd405c6a2)

Kindly assign this issue to me

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
already assigned 2 issue complete that first then do this

**Comment by Bhum-ika** [comment]
@dhairyagothi  Kindly assign this, i have completed those two

**Comment by dhairyagothi** [comment]
go for it @Bhum-ika
