### ISSUE TITLE
Add Navigation Bar and Improve Text Visibility

### ISSUE THREAD

**Issue by Aman8471** [Mehtarishita/StationGuide#345]
# 🖥️ Frontend Issue

The current website lacks a navigation bar, making it difficult for users to find key sections. Additionally, text visibility is poor due to low contrast with background colors, negatively impacting readability.

Steps to Reproduce
Open the website.
Observe the absence of a navigation bar at the top.
Review the text for readability issues against the background.
Expected behavior
A fixed, responsive navigation bar should be present at the top of the page, allowing easy access to key sections (Home, About, Services, Contact). Text should be clear and easily readable.

Actual behavior
There is no navigation bar, and text is hard to read due to low contrast with the background.

Screenshots or Video
![Uploading Screenshot 2024-10-20 213926.png…]()

Are you participating in GSSoC?
 Yes

**Comment by dhairyagothi** [comment]
do changes according to FIGMA UI only read documentation @Aman8471

**Comment by Aman8471** [comment]
please assign me the level
