### ISSUE TITLE
No requirement for scroll bar

### ISSUE THREAD

**Issue by spc-28** [Mehtarishita/StationGuide#349]
# 🖥️ Frontend Issue

### **Description**
There is a scroll bar appearing at the side which i think is not appealing to the ui.

### **Steps to Reproduce**

1. Go to Home page
2. You will see a scroll bar of blue colour on the right side.

### **Expected behavior**
There should be no scroll bar.

### **Screenshots or Video**
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/7c30cd09-22cd-4695-8bef-e26b70ceb774">

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
decrease its width or enhance it more @spc-28
