### ISSUE TITLE
Suggestion to add footer in the website

### ISSUE THREAD

**Issue by akshattiwarii** [Mehtarishita/StationGuide#35]
# ✨ Feature Request

### **Description of the Feature**

Wanted to adding footer in the website for more user attractive.

### **Problem Statement**

I will add footer section with all the features as per website requirement.

### **Proposed Solution**

![Screenshot from 2024-10-02 16-47-55](https://github.com/user-attachments/assets/251e2b6b-2250-410d-844b-8de8a9f25961)

### **Alternatives Considered**

N/A

### **Additional Context**

Adding all liks that redirect to that page directly and also adding social media links.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
it will make UI bad 
check 
https://github.com/dhairyagothi/StationGuide/blob/main/StationGuideFigma.md

**Comment by akshattiwarii** [comment]
sir I want to add footer in website not in the app

**Comment by dhairyagothi** [comment]
> sir I want to add footer in website not in the app

Bro it is the mobile design we are developing web-app which will look like figma design in mobile view

**Comment by akshattiwarii** [comment]
Ohh sorry I don't read the README file clearly, sorry for that.

**Comment by dhairyagothi** [comment]
> Ohh sorry I don't read the README file clearly, sorry for that.

no problem brother
