### ISSUE TITLE
Bug: Auto comment github bot not functioning. 

### ISSUE THREAD

**Issue by spc-28** [Mehtarishita/StationGuide#350]
# 🐞 Bug Report

### **Describe the bug**
The auto comment bot which appears after raising an issue, has contributing md link which is not working correctly. It opens the same issue on which it was clicked.

### **Steps to Reproduce**
1. Go to 'any issue'.
2. Click on the Contributing.md in github-actions bot comment.

### **Expected behavior**
It should redirect to Contributing.md

### **Actual behavior**
Its redirecting to same issue in which it was clicked.

Please assign this issue to me so i can create a PR.

**Comment by dhairyagothi** [comment]
its working

**Comment by spc-28** [comment]
i m using mac and also i have checked on mobile phone 
<img width="294" alt="image" src="https://github.com/user-attachments/assets/4037c014-e817-4669-898d-30bdbfb98534">
on clicking the above button its redirecting me to the same issue not the Contributing.md file.
browser-> Chrome

**Comment by spc-28** [comment]
<img width="376" alt="Screenshot 2024-10-21 at 2 55 11 PM" src="https://github.com/user-attachments/assets/108c1b51-466e-4aad-b07f-61eeeb103e4d">
see on hovering over the link below is the link over which it will be redirected.

**Comment by spc-28** [comment]
@dhairyagothi
