### ISSUE TITLE
Fix the Screen Alignment and Responsiveness Issues

### ISSUE THREAD

**Issue by arcane-2004** [Mehtarishita/StationGuide#36]
# 🖥️ Frontend Issue

### **Description**
The interface displays several alignment challenges when viewed on various screen sizes. Key elements like the "Station Saarthi" marker and the welcome text ("Namaste!! Yatree") are not properly aligned and can appear misplaced or overlapping on different screens. Similarly, the buttons for "Login" and "Register" may not adjust proportionally, leading to distorted layout on smaller or larger displays.

The icons at the bottom for "Navigation," "Booking," and "Services" also exhibit poor responsiveness. Without proper scaling, these icons risk being squished or scattered, resulting in an inconsistent user experience. These issues highlight the need for a responsive design that adapts fluidly to different screen dimensions, ensuring that all elements remain properly aligned and accessible across devices.

### **Steps to Reproduce**
1. Go to home page
2. Right click and Inspect
3. Change the window size to different sizes like phone, tablet etc.

### **Expected behavior**
 A responsive interface is that all elements, including the "Station Saarthi" marker, welcome text, buttons, and icons, should scale proportionally across different screen sizes. The layout should adjust dynamically to maintain consistent alignment and spacing, ensuring that no elements overlap or become misaligned. On smaller screens, elements should resize and stack appropriately, while maintaining clarity and ease of use, providing a seamless and visually balanced experience on all devices.

### **Screenshots or Video**
![{36BEB4DE-1252-4B83-8ECE-16D2E7F324AA}](https://github.com/user-attachments/assets/a90e2d44-557c-43af-bd01-2fd9124f9635)

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by arcane-2004** [comment]
Please assign this issue to me and also add labels.

**Comment by dhairyagothi** [comment]
Assigned @arcane-2004 

Make PR asap

**Comment by dhairyagothi** [comment]
@arcane-2004 updates ?
