### ISSUE TITLE
Privacy & Policy Page

### ISSUE THREAD

**Issue by TanmayKalra09** [Mehtarishita/StationGuide#362]
# ✨ Feature Request

### **Description of the Feature**
We can implement a Proper privacy & policy page on the website's footer.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by Sonuu20** [comment]
I would also like to work on this feature

**Comment by dhairyagothi** [comment]
good one and first PR i will merge with Level 2

**Comment by TanmayKalra09** [comment]
@dhairyagothi thank you so much for assigning the issue

**Comment by TanmayKalra09** [comment]
Hi, @Sonuu20 
I have already started working on this and will raise a PR for the same soon. If you dont mind can you pick any other issue/feature-enhancement.
cc: @dhairyagothi

**Comment by dhairyagothi** [comment]
Sure @TanmayKalra09  make PR i will see

**Comment by TanmayKalra09** [comment]
Hey @dhairyagothi I have raised the [PR](https://github.com/dhairyagothi/StationGuide/pull/382). Please review it once.
