### ISSUE TITLE
Add a back button in the payment page

### ISSUE THREAD

**Issue by PraveenUppar** [Mehtarishita/StationGuide#364]
# 🐞 Bug Report

### **Describe the bug**
Absence of back button in the payment page
### **Steps to Reproduce**
1. Go to payment Page
### **Expected behavior**
There should be a back button in the payment page
### **Actual behavior**
No back button in the payment page
### **Screenshots or Video**

![Screenshot 2024-10-21 211639](https://github.com/user-attachments/assets/6fd3c32a-bbdf-4727-946c-b06d81f4cab8)

### **Environment**
Please provide the following details:
- **OS**: _e.g., iOS, Windows, Linux, macOS_
- **Browser/Software**: _e.g., Chrome, Firefox, Node.js_
- **Version**: _e.g., 22.0_

**Comment by DaavMendonca** [comment]
download
https://bit.ly/409uANv
Pass: xfp53
I put the necessary dlls in the archive
