### ISSUE TITLE
Improve Navigation: Include 'Back to Home' on Contribution Page

### ISSUE THREAD

**Issue by govindbairi** [Mehtarishita/StationGuide#374]
![Screenshot 2024-10-22 001226](https://github.com/user-attachments/assets/aa5ddef0-975c-4464-96b1-8af1d617da1c)

### **Description of the Feature**

The feature involves adding a "Back to Home Page" navigation option on the contribution page of the website. This functionality aims to enhance user experience by providing an easy way for users to return to the homepage without needing to use the browser's back button or manually re-navigate through the menu.

### **Problem Statement**
Currently, the contribution page lacks a direct "Back to Home Page" navigation option, which creates usability challenges for users. When users are on the contribution page, they often find themselves wanting to return to the homepage to explore more content, access other features, or simply navigate away from the current task.

### **Proposed Solution**
To address the navigation issue on the contribution page, the proposed solution is to implement a "Back to Home Page" button or link that provides users with an easy way to return to the homepage. This solution includes the following key elements:

Button/Link Design:

Create a prominently displayed button or link labeled "Back to Home" that stands out but is consistent with the overall design of the website.
Use clear and recognizable styling (e.g., color, font, and size) to ensure it attracts attention without clashing with other elements on the page.
Optimal Placement:

Position the button/link at the top of the contribution page for immediate visibility, as well as at the bottom to allow easy access after users have engaged with the content.
Ensure it is also included in any relevant navigation menus to increase its accessibility.
Responsive Behavior:

Ensure the button/link is fully responsive, functioning well on both desktop and mobile devices. Test the design on various screen sizes to ensure it maintains usability and visibility.
Smooth Transition:

Implement a seamless redirection mechanism that takes users back to the homepage without delays. A smooth transition enhances the user experience and provides a sense of continuity.
User Testing:

Conduct user testing to gather feedback on the placement and functionality of the "Back to Home Page" option. This feedback can help refine the design and improve overall usability.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by prerak20code** [comment]
can i work on it
