### ISSUE TITLE
Adding Dark mode feature in website

### ISSUE THREAD

**Issue by SanchayCoder06** [Mehtarishita/StationGuide#378]
# ✨ Feature Request

### **Description of the Feature**
Dark mode for the website

### **Problem Statement**
Adding a dark mode switch toggle to convert light mode to dark mode.

### **Proposed Solution**
HTML: Contains a button to trigger the toggle and a heading for context.
CSS: Defines both light and dark mode styles. The dark mode styles are applied when the dark-mode class is added to the body tag.
JavaScript: Adds or removes the dark-mode class from the body and the button when the button is clicked, toggling between dark and light mode.

### **Additional Context**
This solution ensures a smooth transition between themes, and the button itself changes appearance when in dark mode.

### **Are you participating in GSSoC?**
Yes
![image](https://github.com/user-attachments/assets/81631c73-583d-4831-8734-1ded35f0e9f8)

**Comment by dhairyagothi** [comment]
@SanchayCoder06  how will you implement this tell in detail what will you use project is in react read documentation first
