### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by TanmayKalra09** [Mehtarishita/StationGuide#384]
# ✨ Feature Request

### **Description of the Feature**
We can add the social media links of Station Saarthi on the footer so that users can reach out to Station Saarthi on social media as well.

Please Assign this Issue to me :)

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
there is no need of footer please read documentation and check figma UI

**Comment by TanmayKalra09** [comment]
alright, if you don't want the separate footer for them.Can I add them beside the privacy and policy link?

**Comment by dhairyagothi** [comment]
in hamburger?

**Comment by TanmayKalra09** [comment]
yes
