### ISSUE TITLE
Make Menu bar Fixed

### ISSUE THREAD

**Issue by AnanteshG** [Mehtarishita/StationGuide#403]
# 🖥️ Frontend Issue

### **Description**
When scrolling, the menu bar doesn't stay fixed. Which makes it difficult to open the menu bar.

### **Steps to Reproduce**

1. Go to Homepage
2. Scroll and see the menu bar.

### **Expected behavior**
The menu bar stays fixed even while scrolling.

### **Actual behavior**
It moves with the scollbar.

### **Screenshots or Video**

https://github.com/user-attachments/assets/7f0d1550-0053-4801-97b4-de92b9d6fb84

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
its fixed i think @AnanteshG
