### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [Mehtarishita/StationGuide#406]
Issue Description
adding Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership
![2024-10-22 (14)](https://github.com/user-attachments/assets/aa52bf4e-70f8-47df-a681-f01e8f09aef2)

**Comment by amiya-cyber** [comment]
please @dhairyagothi assign me this issue with all the labels
gssoc ext
hacktoberfest
level 2 or level 3

**Comment by dhairyagothi** [comment]
its documentation i can't add lv 2 or 3 

its look great
