### ISSUE TITLE
Readme file and code of conduct enhancement

### ISSUE THREAD

**Issue by itsbhh** [Mehtarishita/StationGuide#41]
Could you please assign this issue to me under GSSOC'24 extd and Hacktoberfest? I would like to work on readme file and code of conduct make it more user-friendly . Thanks!

FEATURES I CAN ADD IF ASSIGNED :
1.navigation: your readme file is long and same goes for code of conduct for making it user friendly there should be navigation.
2.A little preview of code of conduct
3. Contact Information: Including a contact section for users to reach out with questions or suggestions, promoting open communication within the community.
4. A little preview of how to contribute .
5. Visual Design Improvements

**Comment by dhairyagothi** [comment]
Sure @itsbhh leeeesss gooo 🚀

**Comment by anushkaa-dubey** [comment]
I'd love to collaborate on this issue as part of GSSOC'24 and Hacktoberfest! 
I have experience in improving documentation to make it more engaging and user-friendly. 
My contributions will focus on:
-Integrating a contact section to ensure anyone with questions or suggestions can easily reach out, fostering better collaboration.
-Implementing subtle design tweaks for a more visually appealing and accessible document.

Looking forward to the opportunity to improve these elements for the benefit of the entire community.

**Comment by dhairyagothi** [comment]
> I'd love to collaborate on this issue as part of GSSOC'24 and Hacktoberfest! I have experience in improving documentation to make it more engaging and user-friendly. My contributions will focus on: -Integrating a contact section to ensure anyone with questions or suggestions can easily reach out, fostering better collaboration. -Implementing subtle design tweaks for a more visually appealing and accessible document.
> 
> Looking forward to the opportunity to improve these elements for the benefit of the entire community.

Wait for @itsbhh if she not make a PR till tommorow i will assign you

**Comment by dhairyagothi** [comment]
@itsbhh any updates ??

**Comment by itsbhh** [comment]
> @itsbhh any updates ??

Ya Till tomorrow morning you will receive the PR. Worked on Readme now working on code of conduct. Please wait till tomorrow.

**Comment by dhairyagothi** [comment]
> > @itsbhh any updates ??
> 
> Ya Till tomorrow morning you will receive the PR. Worked on Readme now working on code of conduct. Please wait till tomorrow.

Sure
