### ISSUE TITLE
[Feature]Add Google Translate Support 

### ISSUE THREAD

**Issue by jjf2009** [Mehtarishita/StationGuide#416]
# ✨ Feature Request

### **Description of the Feature**
I would like to add google translation to the website so that the website is accessible to everyone 

### **Problem Statement**
the website can be used by only people who know English 

### **Proposed Solution**
I will add a drop-down menu so that people of all languages can access our website

### **Are you participating in GSSoC?**
- [x] Yes

**Comment by dhairyagothi** [comment]
already there fix it using npm library 
tell me only if you can do it
