### ISSUE TITLE
send email when forget password is clicked

### ISSUE THREAD

**Issue by AyushSharma72** [Mehtarishita/StationGuide#419]
# ✨ Feature Request

### **Description of the Feature**
you have a forget password page but it is not working 

### **Proposed Solution**
i want to add an api in the backend so that the user can receive email when clicked on recover password

please assign this issue to me @dhairyagothi 
![image](https://github.com/user-attachments/assets/ff1a064b-30ee-4324-8368-81fef9b0d249)

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
done by recent PR merge #423
