### ISSUE TITLE
FEAT : Add Contact Us page Via E-Mail

### ISSUE THREAD

**Issue by PriyanshuValiya** [Mehtarishita/StationGuide#424]
# ✨ Feature Request

### **Description of the Feature**
This feature lets users contact you via mail from a direct website.

### **Previous Work**
![Screenshot 2024-10-22 210539](https://github.com/user-attachments/assets/fec6e3c6-4110-4dd4-8a98-e7d67c460f6b)

### **User Reviews**
The user told that it is a very useful and time-saving tool.

### **Are you participating in GSSoC?**
-  Yes
- [ ] No

**Comment by dhairyagothi** [comment]
make changes in contact us page only

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi Please assign me the issue I will make the sure the working of the frontend and backend implementations

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi please assign me here
