### ISSUE TITLE
Slow Cursor Animation on Railway Station Page

### ISSUE THREAD

**Issue by Aayushibnsl** [Mehtarishita/StationGuide#428]
# 🖥️ Frontend Issue

### **Description**
The cursor animation on the Railway Station page appears to be running very slowly, creating a lag that gives the impression the system is hanging. This affects the user experience, making the interface feel unresponsive and frustrating for users who may be in a time-sensitive environment.

### **Steps to Reproduce**
1.Navigate to the Railway Station page.
2.Move the cursor around the page, especially over interactive elements (buttons, links, etc.).
3.Observe the delay and slowness in the cursor animation.

### **Expected behavior**
The cursor animation should be smooth and responsive, ensuring a seamless user experience without lag or delay.

### **Actual behavior**
The cursor animation moves sluggishly, leading to a stuttered and slow response time.

### Are you participating in GSSoC?
- [ x] Yes
- [ ] No

**Comment by Aayushibnsl** [comment]
Please assign me this . i want to contribut in this

**Comment by haseebzaki-07** [comment]
@dhairyagothi please assign me the issue
