### ISSUE TITLE
Swap Positions of Search and Profile Logo Buttons

### ISSUE THREAD

**Issue by Aayushibnsl** [Mehtarishita/StationGuide#429]
# 🖥️ Frontend Issue

### **Description**
The search and profile logo buttons are currently positioned such that when a user initiates a search, the profile logo moves out of view or to the back, making it difficult to access while searching. To improve usability, these two buttons should switch positions, allowing the profile button to remain visible during a search.

### **Steps to Reproduce**
1.Navigate to the page where the search and profile buttons are displayed.
2.Initiate a search action.
3.Notice that the profile logo is pushed out of visibility or obstructed while typing.

### **Expected behavior**

The profile logo should remain visible and easily accessible during search actions.But while searching it should not show

### **Actual behavior**

The search view becomes harder to access because profile logo is showing in back

### Are you participating in GSSoC?
- [x ] Yes
- [ ] No

**Comment by Aayushibnsl** [comment]
Please assign me this

**Comment by dhairyagothi** [comment]
its okay @Aayushibnsl
