### ISSUE TITLE
Add Search Placeholder Text for Train Name or Train Number

### ISSUE THREAD

**Issue by Aayushibnsl** [Mehtarishita/StationGuide#430]
# 🖥️ Frontend Issue

### **Description**
When clicking on the search icon, the input field opens and prompts the user to type, but there is no guidance on what information they should enter, such as "train name" or "train number." This can lead to confusion, as users may not know the expected search format or criteria.

### **Steps to Reproduce**
1.Click on the search icon on the page.
2.Observe that the search input field appears but lacks any placeholder text indicating what to search for.

### **Expected behavior**
The search field should display a placeholder text, such as “Search by train name or number,” to guide users on the type of information to enter.

### **Actual behavior**
The search field opens without any guidance, leaving users uncertain about the search criteria.

### Are you participating in GSSoC?
- [ x] Yes
- [ ] No

**Comment by Aayushibnsl** [comment]
Please assign me this

**Comment by TanmayKalra09** [comment]
hey @Aayushibnsl are you working on this issue or can i pick it up?

**Comment by Aayushibnsl** [comment]
Yes, I am working on it.
