### ISSUE TITLE
Add Loading Animation on Booking Page After Search

### ISSUE THREAD

**Issue by Aayushibnsl** [Mehtarishita/StationGuide#431]
# 🖥️ Frontend Issue

### **Description**
On the booking page, when a user initiates a search and presses Enter, there is no loading animation to indicate that the system is processing the request. This can cause confusion, as users may think the search isn’t working or that the page has frozen. A loading animation would improve the user experience by providing feedback during the search process.

### **Steps to Reproduce**
1.Navigate to the booking page.
2.Enter search criteria (e.g., train name or number).
3.Press Enter to initiate the search.
4.Observe that there is no loading animation while the results are being fetched.

### **Expected behavior**

After pressing Enter, a loading animation should appear to inform users that the search is in progress.

### **Actual behavior**

No loading animation is shown, leading to a lack of feedback for users while waiting for search results.

### Are you participating in GSSoC?
- [ x] Yes
- [ ] No

**Comment by Aayushibnsl** [comment]
please assign me this

**Comment by haseebzaki-07** [comment]
@dhairyagothi assign me the issue!
