### ISSUE TITLE
Language Does Not Change After Selecting a Different Language

### ISSUE THREAD

**Issue by Aayushibnsl** [Mehtarishita/StationGuide#432]
# 🛠️ Backend Issue

### **Description**
When users select a different language from the language options, the page does not update to display content in the chosen language. This issue can cause confusion, as users expect the page to reflect their language preference immediately.

### **Steps to Reproduce**
1.Go to the language selection menu.
2.Select a language other than the current one (e.g., switch from English to Hindi).
3.Observe that the page content remains in the original language instead of updating to the selected language.

   
### Tech stack required 
Frontend: HTML, CSS, JavaScript, React, Angular, Vue.js
Backend: Node.js, Django, Ruby on Rails
Localization Libraries: i18next, react-intl, Globalize
API: RESTful API, GraphQL
Database: MySQL, MongoDB, PostgreSQL
Caching: Redis, Memcached
Deployment: Docker, Kubernetes

### **Are you participating in GSSoC?**
- [x ] Yes
- [ ] No

**Comment by Aayushibnsl** [comment]
please assign me this

**Comment by dhairyagothi** [comment]
you know how to use npm google api libraray ??
