### ISSUE TITLE
Lanaguage doesn't change In Hindi

### ISSUE THREAD

**Issue by 1754riya** [Mehtarishita/StationGuide#436]
After selecting Language, it doesn't change.
![Screenshot (371)](https://github.com/user-attachments/assets/a37172c0-470c-4ec2-a264-a0f49b38b9fa)

@dhairyagothi ,Please assign me under Gssoc'24 and Hacktoberfest.

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi can I take the issue??

**Comment by dhairyagothi** [comment]
> hey @dhairyagothi can I take the issue??

It is already solved @haseebzaki-07
