### ISSUE TITLE
Privacy and Policy must be aligned 

### ISSUE THREAD

**Issue by 1754riya** [Mehtarishita/StationGuide#437]
Privacy and Policy must be aligned to provide better visuals, it is overlapping, 

![Screenshot (370)](https://github.com/user-attachments/assets/d1560c6d-0737-49f6-aaa3-1ae867d2e0d0)

@dhairyagothi , please assign me under Gssoc'24 and Hacktoberfest.

**Comment by Shalinis19137** [comment]
I really like your application and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by dhairyagothi** [comment]
> I really like your application and want to work on your project ,please assign this issue to me under gssoc-ext 2024

Make PR asap
