### ISSUE TITLE
Adding a header

### ISSUE THREAD

**Issue by varshapandiann** [Mehtarishita/StationGuide#438]
# ✨ Feature Request

### **Description of the Feature**
A functioning header with enhanced UI for improved user experience

### **Problem Statement**
There is no navigation from the various pages to different pages. One must always come back to the homepage using the basic UI and then further navigate to a different page. This can be changed to navigate between the different pages using a header

### **Proposed Solution**
I want to add a header to improve the navigation to and from different pages.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
check figma design bro no need
