### ISSUE TITLE
Subscribe to the platform

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#441]
# ✨ Feature Request

### **Description of the Feature**
make a frontend component where users can fill in their mail ids and can subscribe the platform

### **Problem Statement**
It will let the users be subscribed to receive updates of the website.

### **Proposed Solution**
A backend API for sending confirmation mails to the users after they fill in their valid mail ids, also update the user schema to add the field subscribe

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
add it in popup

**Comment by haseebzaki-07** [comment]
@dhairyagothi assign me, will do it.
