### ISSUE TITLE
Improve Background Visibility for Enhanced Readability

### ISSUE THREAD

**Issue by swati-204** [Mehtarishita/StationGuide#447]
# 🖥️ Frontend Issue

### **Description**
Hero Section is not impressive the background is not Appealing which makes the text visibility issue affect the user experience.

### **Steps to Reproduce**

1. Go to 'Station Saarthi'
2. Click on 'Hero Section'
3. See error '...'

### **Expected behavior**
The background should provide improved visibility, making text and other elements clear and easy to interact with.

### **Actual behavior**
The current background lacks contrast, making text and elements difficult to read. Improving the background visibility will enhance user experience and accessibility.

### **Screenshots or Video**
![Video Screen1730095287580](https://github.com/user-attachments/assets/d8e32758-b8c1-40a1-b8cb-d65273040caa)

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by swati-204** [comment]
can you assign this to me ? @dhairyagothi

**Comment by dhairyagothi** [comment]
Assigned @swati-204 please make PR before 31 October

**Comment by swati-204** [comment]
> Assigned @swati-204 please make PR before 31 October

Yeah! I will submit it by today.

**Comment by swati-204** [comment]
@dhairyagothi I'm having trouble opening the backend, I've installed all the dependencies and it still throws an error.
