### ISSUE TITLE
add forgot password functionality

### ISSUE THREAD

**Issue by AyushSharma72** [Mehtarishita/StationGuide#449]
i want to add forgot password functionality to the login form 
with both frontend page and backend api 

![image](https://github.com/user-attachments/assets/d0f0251f-312a-4e8c-b5ec-991d1b66d7a5)

please assign this issue to me @dhairyagothi

**Comment by dhairyagothi** [comment]
![image](https://github.com/user-attachments/assets/2226ee96-18e9-4635-9ae9-e4be58831f0b)

already there it is not visible

**Comment by AyushSharma72** [comment]
There is some error I will resolve it 
![Screenshot_2024-10-30-11-41-23-92_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/03dcb1d0-2436-4715-885e-2a57eb99062a)

@dhairyagothi
