### ISSUE TITLE
Text in white on home page not quite visible

### ISSUE THREAD

**Issue by shreya2k3** [Mehtarishita/StationGuide#454]
# 🐞 Bug Report

### **Describe the bug**
"Station Saarthi: Your platform guide" is written in white color. 

### **Steps to Reproduce**
1. Go to website
2. See error on home page.

### **Expected behavior**
To be more visible, it should be written in black.

### **Actual behavior**
The text is written in white which is not looking good at a light background.

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/c3d0529b-3409-46ab-afaf-229d5fe4d30d)

**Comment by shreya2k3** [comment]
@dhairyagothi pls assign the issue to me

**Comment by dhairyagothi** [comment]
what colour you will do then ??

make it visible use tailwind

**Comment by shreya2k3** [comment]
> what colour you will do then ??
> 
> make it visible use tailwind

Ok, I will see to it and will try to make it more clear

**Comment by im-ShreyaGupta** [comment]
@dhairyagothi pls assign this issue to me

I will change it to
![Screenshot 2024-11-01 191417](https://github.com/user-attachments/assets/37da12dc-a58b-4084-9d65-95b06f1ff1b0)
 
You can suggest any other desired change if it does not look good to you.
