### ISSUE TITLE
No way to navigate back from the Contributors page

### ISSUE THREAD

**Issue by saras-69** [Mehtarishita/StationGuide#456]
# 🐞 Bug Report

### **Describe the bug**

There is no option to return to the previous page after visiting the Contributors page, which disrupts navigation.

### **Steps to Reproduce**
Go to the homepage.
Click on the "Contributors" link.
Attempt to navigate back to the previous page.
Notice that there is no back button or link available.

### **Expected behavior**

There should be a visible back navigation option or button that allows users to return to the previous page.

### **Actual behavior**

Users are unable to navigate back from the Contributors page, leading to confusion and a poor user experience.

### **Environment**
Please provide the following details:
- **OS**: _e.g., iOS, Windows, Linux, macOS_
- **Browser/Software**: _e.g., Chrome, Firefox, Node.js_
- **Version**: _e.g., 22.0_

**Comment by dhairyagothi** [comment]
fixed by last PR
