### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jainaryan04** [Mehtarishita/StationGuide#469]
@dhairyagothi 
# ✨ Feature Request 

### **Description of the Feature**
Implementing dark mode improves user comfort by reducing eye strain and glare, especially in low-light environments. It enhances readability, conserves battery on OLED devices, and aligns with modern design practices. Supporting dark mode will offer a better user experience and accessibility, catering to diverse user preferences.

### **Proposed Solution**
Dark mode can be implemented using a custom React hook to manage theme state. The hook toggles between light and dark themes, updating the class on the root element. CSS classes (e.g., .dark or .light) control styling. The hook listens to system preferences and persists the theme in localStorage.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by Dhruv-pahuja** [comment]
can i also work on it , so i that i can finish this quickly withint a hour @dhairyagothi

**Comment by dhairyagothi** [comment]
@Dhruv-pahuja go ahead

**Comment by jainaryan04** [comment]
@dhairyagothi I am working on it already

**Comment by dhairyagothi** [comment]
> @dhairyagothi I am working on it already

YOU KEEP WORKING DON'T WORRY ABOUT ASSIGNING

JUST MAKE PR ASAP

**Comment by Dhruv-pahuja** [comment]
Sorry for removing my assignments because of ongoing exams in my college , I will be very busy and unable to work on this issue till next saturday @dhairyagothi

**Comment by dhairyagothi** [comment]
> Sorry for removing my assignments because of ongoing exams in my college , I will be very busy and unable to work on this issue till next saturday @dhairyagothi 

Okay no problem
