### ISSUE TITLE
[Backend Issue]:  Add nodemon to Dev Dependencies for Easier Development

### ISSUE THREAD

**Issue by rishyym0927** [Mehtarishita/StationGuide#47]
### **Description**
The development process can be streamlined by adding `nodemon` to the project's dev dependencies. `nodemon` automatically restarts the server when file changes are detected, making development faster and more efficient.

### **Steps to Reproduce**
1. Start working on the project.
2. Make changes to backend files.
3. Notice that the server needs to be manually restarted after each change.

### **Tech stack required**
- Node.js
- Familiarity with `nodemon` for auto-restarting the server during development

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
already there
