### ISSUE TITLE
Cursor Follower Not Tracking Properly: Cursor Lag or Misalignment

### ISSUE THREAD

**Issue by AaryaShrivaastava** [Mehtarishita/StationGuide#474]
# 🖥️ Frontend Issue

### **Description**
The multicolored cursor follower gets too far from the cursor if one switches tabs or the cursor returns to the web page after navigating the system taskbar. 

### **Expected behavior**
The cursor follower should move along with the cursor, even with some time lag but the cursor should be overlap the follower.

### **Actual behavior**
The follower is far away from the cursor. If there is some time lag, it is fine but there seems some issue with the frontend followup of the cursor.

### Are you participating in GSSoC?
- [x] Yes

**Comment by AaryaShrivaastava** [comment]
Thank you for your response! The issue I’m experiencing is specific to the misalignment of the cursor follower, especially when switching between tabs or when the home page is scrolled. After a tab change or after scrolling through the website, the follower appears offset from the cursor, which affects the overall user experience.

I did notice a previously raised issue regarding the cursor follower being slow and laggy. However, my concern is more about the follower’s position rather than its speed.

Please let me know if there's any further information or specific tests I can provide to help address this.  Also, I would really appreciate if you add the gssoc extd label. Thank you!

**Comment by dhairyagothi** [comment]
@AaryaShrivaastava go for it take your time and make PR
