### ISSUE TITLE
Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by itshivams** [Mehtarishita/StationGuide#479]
The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag
@dhairyagothi  Please assign this issue to me (@myselfshivams).

Labels:
GSSoC

**Comment by itshivams** [comment]
Hi @dhairyagothi , Could you please add a higher-level tag, as I have devoted a significant amount of time to this?

**Comment by dhairyagothi** [comment]
> Hi @dhairyagothi , Could you please add a higher-level tag, as I have devoted a significant amount of time to this?

POINTS ARE ASSIGNED ON BASIS OF LABEL ON PR
