### ISSUE TITLE
Create a Custom 404 Page for Better User Experience

### ISSUE THREAD

**Issue by itshivams** [Mehtarishita/StationGuide#480]
Currently, when users encounter a broken or non-existent link, the website shows the default 404 error page. To enhance the user experience, we should create a custom 404 page with a user-friendly design and helpful navigation options (e.g., a link back to the homepage or other important sections). This will help guide users when they land on a missing page, improving overall usability.

Labels:
gssoc

@dhairyagothi  Please assign this task to me (@myselfshivams).

**Comment by dhairyagothi** [comment]
already there @myselfshivams check after running in local not visible in deployment

**Comment by Abhixhek8** [comment]
check after running it locally.

**Comment by dhairyagothi** [comment]
> check after running it locally.

Yesss
