### ISSUE TITLE
Improved the UI of Login and Register Pages.

### ISSUE THREAD

**Issue by Premkolte** [Mehtarishita/StationGuide#49]
# 🖥️ Frontend Issue

### **Description**
Changes the background. and improved UI

### **Actual behavior**

<img width="1440" alt="Screenshot 2024-10-03 at 9 55 29 PM" src="https://github.com/user-attachments/assets/18187290-7be6-4cbc-9535-b078f602d091">

<img width="1440" alt="Screenshot 2024-10-03 at 9 56 01 PM" src="https://github.com/user-attachments/assets/d6f5711e-8963-4ea8-861a-71c2ca89a1ca">

### **Screenshots or Video**

<img width="1440" alt="Screenshot 2024-10-03 at 9 56 18 PM" src="https://github.com/user-attachments/assets/d0aca7cf-959e-4756-aa4d-46eae2108411">

<img width="1440" alt="Screenshot 2024-10-03 at 9 56 33 PM" src="https://github.com/user-attachments/assets/1e2832b6-5118-479e-971f-485941ddcc44">

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by Premkolte** [comment]
@dhairyagothi, any more changes you want me to make?

or shall I do a PR?

**Comment by dhairyagothi** [comment]
in login page add 
Your Platform Guide 

and a login heading 
and make PR
