### ISSUE TITLE
Forgot password link is not visible 

### ISSUE THREAD

**Issue by VinayLodhi1712** [Mehtarishita/StationGuide#490]
# 🖥️ Frontend Issue

### **Description**
Forgot password link is not visible 

### **Steps to Reproduce**

go to login page it is not clearly visible

### **Screenshots or Video**

![not showing for got ](https://github.com/user-attachments/assets/dad633cc-26ea-4640-b0bd-9eff9b43f7b2)

### Are you participating in GSSoC?
- [ X] Yes
- [ ] No

**Comment by Roshan-anand** [comment]
hey please assign it to me i'll solve it
