### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by haseebzaki-07** [Mehtarishita/StationGuide#493]
# ✨ Feature Request

### **Description of the Feature**
users forgetting password should be allowed to reset their passwords.

### **Problem Statement**
helpful to recover users accounts if they forget the password.

### **Proposed Solution**
Will be sending otp to their mail ids for recovering the account and resetting the password.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by mehul-m-prajapati** [comment]
Duplicate #449 @haseebzaki-07
