### ISSUE TITLE
UI ISSUE IN REGISTRATION PAGE [Image overflowed]

### ISSUE THREAD

**Issue by rishyym0927** [Mehtarishita/StationGuide#50]
# 🖥️ Frontend Issue

### **Description**
the background image overflowed

### **Steps to Reproduce**

1. Go to 'register '

### **Expected behavior**

the background should be clear with no overflow

### **Actual behavior**

there should be no overflow in the image

### **Screenshots or Video**

![image](https://github.com/user-attachments/assets/15d0ce4e-8fb1-4d7a-b62f-a6e90070dad3)

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
its fine @rishyym0927 we need that whitish bg
