### ISSUE TITLE
Sign-in, Login with Google option is not Responsive

### ISSUE THREAD

**Issue by sania-2912** [Mehtarishita/StationGuide#502]
🐞 Bug Report

Sign-in, Login with Google option is not Responsive

Describe the bug
The "Sign-in" and "Login with Google" buttons are not responsive on the page, meaning they do not adapt well to different screen sizes or mobile views.

Steps to Reproduce
Go to the login page where the "Sign-in" and "Login with Google" buttons are located.
Attempt to resize the window or access the page from a mobile device.
Observe that the buttons do not scale or adjust correctly, leading to layout issues.

Expected Behavior
The "Sign-in" and "Login with Google" buttons should be fully responsive, adjusting in size and placement to fit various screen sizes, especially mobile displays.

### **Screenshots or Video**

https://github.com/user-attachments/assets/f518184e-fa05-4172-b734-2b1e6ef40862

### **Environment**
Please provide the following details:
- OS- Windows
- Browser-Chrome

**Comment by sania-2912** [comment]
@dhairyagothi kindly assign me this issue

**Comment by dhairyagothi** [comment]
Assigned @sania-2912
