### ISSUE TITLE
Source and Destination-Based Ticket Availability Display

### ISSUE THREAD

**Issue by ash-k121** [Mehtarishita/StationGuide#51]
# ✨ Feature Request

### **Description of the Feature**
Implement a feature where users can input their source (departure location) and destination (arrival location) to search for available tickets. After submitting their travel details, the system will display a list of available tickets, including travel times, prices, and options (bus, train, flight, etc.).

### **Problem Statement**
Currently, users may find it difficult to quickly search and view available tickets for their desired travel route. This feature will streamline the ticket search process, allowing users to easily input their source and destination to find the most relevant options, saving time and improving the booking experience

### **Proposed Solution**
The system will:

Provide input fields for users to enter their source and destination.
Once the details are submitted, the backend will query available travel options (bus, train, flight, etc.).
Display the results in a user-friendly interface, including travel times, ticket prices, and filtering options (e.g., by price, time, or type of transport).

### **Additional Context**
NA

### **Are you participating in GSSoC?**
- [ ] Yes

**Comment by dhairyagothi** [comment]
@ash-k121 add in booking section

**Comment by haseebzaki-07** [comment]
@dhairyagothi should I implement the backend of it!!
