### ISSUE TITLE
3D Mapping Not Working

### ISSUE THREAD

**Issue by codewithMohak** [Mehtarishita/StationGuide#514]
# 🐞 Bug Report

Describe the bug
3D mapping is not working as expected. The feature is supposed to provide a 3D map view, but it fails to load or display correctly.

Steps to Reproduce

Go to the 3D Maps section.

Click on the 'Start Mapping' button.

Scroll down to the map display area.

See error where the 3D map does not load or display.

Expected behavior
The 3D map should load and display a three-dimensional view of the selected area.

Actual behavior
The 3D map fails to load or display, showing either a blank screen or an error message.

Screenshots or Video
![Screenshot 2024-11-07 001346](https://github.com/user-attachments/assets/98785592-2920-4503-9962-0f1df8515228)

![Screenshot 2024-11-07 001917](https://github.com/user-attachments/assets/54c19459-504f-41d0-805e-69f4d83e5d9a)

**Comment by dhairyagothi** [comment]
use mapbox @codewithMohak
