### ISSUE TITLE
[Backend Issue]: Cursor Interference Due to Small Animated Elements

### ISSUE THREAD

**Issue by codewithMohak** [Mehtarishita/StationGuide#515]
🛠️ Backend Issue
Description
The cursor is not functioning properly due to small animated elements that are interfering with user interactions. This requires multiple clicks to perform actions such as searching or booking. The issue might be related to how the backend handles UI/UX rendering.

Steps to Reproduce
Navigate to the search or booking section.

Attempt to click on the search or booking button.

Observe that the cursor gets obstructed by small animated elements, requiring multiple clicks to complete the action.

Tech Stack Required
Frontend: HTML, CSS, JavaScript (or relevant frameworks)

Backend: Node.js, Express (or relevant frameworks)

Database: MongoDB (or relevant databases)

Debugging Tools: Chrome DevTools (or relevant tools)

Are you participating in GSSoC?
YES ( Open Source Contributor)

https://github.com/user-attachments/assets/bc096bea-839a-43a0-9dba-b0c4c80501fa

**Comment by dhairyagothi** [comment]
please resolve it asap @codewithMohak
