### ISSUE TITLE
Adding MultiLanguage Facility

### ISSUE THREAD

**Issue by Ojas-Arora** [Mehtarishita/StationGuide#52]
# ✨ Feature Request

### **Description of the Feature**
@dhairyagothi I want to add Multilanguage Facility to the website. Kindly assign me this issue.

### **Proposed Solution**
Multilanguage Facility can allow to read with desired Languages.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Go ahead @Ojas-Arora

**Comment by Ojas-Arora** [comment]
@dhairyagothi Can u pls tell how to start project on local as using using cd frontend and npm run dev it is not working even with node js installed

**Comment by dhairyagothi** [comment]
> @dhairyagothi Can u pls tell how to start project on local as using using cd frontend and npm run dev it is not working even with node js installed

share ss

**Comment by Ojas-Arora** [comment]
![image](https://github.com/user-attachments/assets/632a8549-7396-4fba-a2c0-d3e4dd197425)

**Comment by dhairyagothi** [comment]
run ```npm i vite```

> ![image](https://private-user-images.githubusercontent.com/127867874/373380501-632a8549-7396-4fba-a2c0-d3e4dd197425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMTM1NjQsIm5iZiI6MTcyODAxMzI2NCwicGF0aCI6Ii8xMjc4Njc4NzQvMzczMzgwNTAxLTYzMmE4NTQ5LTczOTYtNGZiYS1hMmMwLWQzZTRkZDE5NzQyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQwMzQxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGY1NDY5YWVjYWQ3OTE0NWU1YzJiYzdiNWRmODk5NWQ3YzEwYTgyYjhmOGY5ODM4NzQzY2M1OTEyNWQ1NmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cBihHO7gWrsmLmPHIHiKvN_iBGyVtmaImZScRJG902Q)
