### ISSUE TITLE
Adding Chatbot

### ISSUE THREAD

**Issue by Ojas-Arora** [Mehtarishita/StationGuide#53]
# ✨ Feature Request

### **Description of the Feature**
@dhairyagothi I want to add a working Chatbot to the website. Kindly assign me this issue.

### **Proposed Solution**
The working chatbot can be used to ask any questions.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Suree bro go ahead check figma file before starting 
StationGuideFigma.md

https://github.com/dhairyagothi/StationGuide/blob/c484e453354675c9bf1b3a5422af3e0f40410eee/StationGuideFigma.md

**Comment by Ojas-Arora** [comment]
@dhairyagothi Can I add my own different chatbot rather than the chatbot mentioned in the figma file?

**Comment by dhairyagothi** [comment]
> @dhairyagothi Can I add my own different chatbot rather than the chatbot mentioned in the figma file?

Ui should be same 
Which tech stack you are using ??
it should be a personalized chatbot with questions not fetched from google or it must not redirect to google

**Comment by Ojas-Arora** [comment]
@dhairyagothi It's an Inbuilt Chatbot which uses AI to answer the queries.

**Comment by dhairyagothi** [comment]
okay integrate it 
Share ss / video of your chatbot

**Comment by Ojas-Arora** [comment]
![image](https://github.com/user-attachments/assets/9b77c6b8-aa8d-412d-970c-3b0d2289774f)

**Comment by dhairyagothi** [comment]
change it with ui
