### ISSUE TITLE
[Fixes] : Add login and Register functionalities

### ISSUE THREAD

**Issue by ak3264114** [Mehtarishita/StationGuide#60]
# 🖥️ Frontend Issue

### **Description**

Login and Register is not functional

### **Steps to Reproduce**

1. Go to Login or Register page
2. Enter your credentials and try to login or register
3. you can see that both the button is not functional

### **Expected behavior**

It should send a request to backend and get a response as well 

### **Actual behavior**

It is not sending and request to backend

### **Screenshots or Video**

![image](https://github.com/user-attachments/assets/f0b145d1-a254-4655-b4d8-cbf8681d4cd7)
![image](https://github.com/user-attachments/assets/105a721d-31eb-4793-9244-bff314ab1af3)

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
@ak3264114 backend is already added check it and make necessary changes . 

I will give level after checking PR 

Thanks go ahead

**Comment by dhairyagothi** [comment]
completed
