### ISSUE TITLE
improving and adding button for close in login page

### ISSUE THREAD

**Issue by Aditijainnn** [Mehtarishita/StationGuide#62]
![image](https://github.com/user-attachments/assets/37396934-1e40-454e-9258-cc41a872182b)
in this login page we can't go back without logging until we refresh page so adding closing button in both sign-in/sign-up page 
please assign this issue to me under gossc ext and hacktoberfest

**Comment by dhairyagothi** [comment]
Good notice @Aditijainnn 

Please add it as in figma design 

You copy svg of back icon from 

https://www.figma.com/design/EkIXVrH4wyDIE3oyJZpCkK?node-id=


Add in both login and registration page 

Ask me if you have any doubt

**Comment by Aditijainnn** [comment]
> Good notice @Aditijainnn
> 
> Please add it as in figma design
> 
> You copy svg of back icon from
> 
> https://www.figma.com/design/EkIXVrH4wyDIE3oyJZpCkK?node-id=
> 
> Add in both login and registration page
> 
> Ask me if you have any doubt

i have sent you the request to grant the access of figma svg icon

**Comment by dhairyagothi** [comment]
> > Good notice @Aditijainnn
> > 
> > Please add it as in figma design
> > 
> > You copy svg of back icon from
> > 
> > https://www.figma.com/design/EkIXVrH4wyDIE3oyJZpCkK?node-id=
> > 
> > Add in both login and registration page
> > 
> > Ask me if you have any doubt
> 
> i have sent you the request to grant the access of figma svg icon

Sorry let me share with access although i have approved it
https://tinyurl.com/44wkf5hs

**Comment by Aditijainnn** [comment]
> > > Good notice @Aditijainnn
> > > Please add it as in figma design
> > > You copy svg of back icon from
> > > https://www.figma.com/design/EkIXVrH4wyDIE3oyJZpCkK?node-id=
> > > Add in both login and registration page
> > > Ask me if you have any doubt
> > 
> > 
> > i have sent you the request to grant the access of figma svg icon
> 
> Sorry let me share with access although i have approved it https://tinyurl.com/44wkf5hs

ok thank you can i complete this issue in a day or 2? 
because i have my midterm exam going on
