### ISSUE TITLE
layout: Home Page Layout is Not User-Friendly

### ISSUE THREAD

**Issue by userAdityaa** [Mehtarishita/StationGuide#63]
# 🖥️ Frontend Issue

### **Description**

The current home page layout lacks user-friendliness, making it difficult for users to navigate and engage with the content. 

### **Expected behavior**

- The home page should have a clean, intuitive layout that allows users to easily find and interact with key sections.
- The overall design should enhance readability and user engagement, without feeling cluttered or overwhelming.

### **Actual behavior**

- The current layout feels cluttered, making it difficult for users to locate important information.
- Visual elements such as typography, spacing, and content alignment are inconsistent, making the page less engaging and harder to read.

### **Screenshots or Video**

<img width="1440" alt="Screenshot 2024-10-05 at 4 51 53 PM" src="https://github.com/user-attachments/assets/d8337e80-3748-4026-9c97-b28508c93a3b">

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by userAdityaa** [comment]
Hey @dhairyagothi, Please assign this to me with the label gssoc and hacktoberfest.

**Comment by dhairyagothi** [comment]
Go ahead @userAdityaa 

I will assign level according to changes in PR

**Comment by abhisek2004** [comment]
Admin Please assign me this task and I'll improve the whole Ui improvement of home page . and i will work on other issues of your website.

**Comment by dhairyagothi** [comment]
> Admin Please assign me this task and I'll improve the whole Ui improvement of home page . and i will work on other issues of your website.

create a new issue
