### ISSUE TITLE
Linking of login and register pages.( routing error )

### ISSUE THREAD

**Issue by Premkolte** [Mehtarishita/StationGuide#65]
# 🖥️ Frontend Issue

### **Description**
when you try to visit register page form login page then it redirects you to some other page.(Not found).

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### **Expected behavior**

<img width="1440" alt="Screenshot 2024-10-05 at 7 11 49 PM" src="https://github.com/user-attachments/assets/636c0128-8076-49ca-9f1b-54074c7fbcd1">

### **Actual behavior**

<img width="591" alt="Screenshot 2024-10-05 at 7 11 18 PM" src="https://github.com/user-attachments/assets/32960b5e-c79d-4db2-9dbe-632aaf7c2f38">

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
It's just one letter change bro 🙂

**Comment by Premkolte** [comment]
yes ik. Don't assign any points for it.

**Comment by Premkolte** [comment]
or
you do that small change.

**Comment by dhairyagothi** [comment]
Okay sure then directly make a PR i will add hacktoberfest-accepted badge it will be counted there

**Comment by Premkolte** [comment]
@dhairyagothi ok, Sir.
