### ISSUE TITLE
 Implement User Authentication and Data Storage using Appwrite

### ISSUE THREAD

**Issue by Atharva-04** [Mehtarishita/StationGuide#66]
# ✨ Feature Request

### **Description of the Feature**
Integrate Appwrite as the backend solution for user authentication and data storage within the Station Guide application. This will allow users to create accounts, log in, and securely manage their profiles.

### **Problem Statement**
Currently, the Station Guide application has a login option but lacks backend logic for user authentication and storing user data. This limits user engagement and personalization.

### **Proposed Solution**
**Set up Appwrite:** Implement Appwrite as the backend service to handle user authentication processes, including registration and login.

**User Registration:** Allow users to create accounts with email and password authentication.

**Secure Login:** Implement secure login functionality, enabling users to access their accounts easily.

**Database Integration:** Create a database within Appwrite to store user profiles, preferences, and any other relevant data. This will ensure that user data is securely managed and easily retrievable.

**Frontend Integration:** Connect the React frontend with Appwrite's API to handle user interactions, such as signing up, logging in, and retrieving user data seamlessly.

### **Alternatives Considered**

Using custom backend solutions (e.g., Node.js with Express) was considered, but it would require more time and resources to implement and maintain compared to Appwrite.

### **Additional Context**
Using Appwrite will streamline the integration process and enhance the application's scalability and security.

### **Are you participating in GSSoC?**
- [x]  Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Go for it @Atharva-04 
Make changes according to Figma design 

And backend database is already there make changes accordingly 

Share SS with PR after doing changes

**Comment by Atharva-04** [comment]
Hi @dhairyagothi, just to clarify, should I integrate Appwrite for user authentication and data storage while keeping the existing MongoDB setup, or do you want me to transition entirely to Appwrite? Thanks!

**Comment by dhairyagothi** [comment]
> Hi @dhairyagothi, just to clarify, should I integrate Appwrite for user authentication and data storage while keeping the existing MongoDB setup, or do you want me to transition entirely to Appwrite? Thanks!

Keep mongoDB it will be good
