### ISSUE TITLE
Enhance UI/UX of Navbar and Revamp Login/Signup Pages with Google Authentication

### ISSUE THREAD

**Issue by ritiksingh-01** [Mehtarishita/StationGuide#68]
# 🖥️ Frontend Issue

### **Description**

The current UI/UX of the navbar lacks aesthetic appeal and usability, negatively impacting user navigation. Additionally, the login and signup pages are not properly connected, creating confusion for users attempting to transition between them.

Furthermore, the eye button for toggling password visibility is missing in the password section, which affects the functionality and user experience of the login interface.

To address these issues, I propose to:

- **Redesign the Navbar:** Improve the overall layout and visual appeal to ensure intuitive navigation.
- **Connect Login and Signup Pages:** Establish clear links between the two pages to facilitate a seamless user experience.
- **Integrate Google Authentication:** Add a login/signup option with Google, providing users with faster and more secure access to their accounts.
- **Implement the Eye Button:** Ensure the eye button is properly placed within the password field to enhance usability.

These updates will significantly improve the user interface and experience, making the platform more user-friendly and accessible.

Kindly assign this issue to me under the GSSoC'24-Extd program.

Thank you for your consideration.
![Uploading train.png…]()
![Uploading login.png…]()

**Comment by dhairyagothi** [comment]
Go ahead @ritiksingh-01

**Comment by ritiksingh-01** [comment]
Hi, @dhairyagothi 

I apologize for the delay in resolving the issue. I'm actively working on it and doing my best to deliver a quality output, as this is my first open-source project. I appreciate your patience, and I will provide the update as soon as possible.

In the meantime, I kindly request that you don’t assign this issue to anyone else or merge any related pull requests. 

Thank you for your understanding!

**Comment by dhairyagothi** [comment]
> Hi, @dhairyagothi
> 
> I apologize for the delay in resolving the issue. I'm actively working on it and doing my best to deliver a quality output, as this is my first open-source project. I appreciate your patience, and I will provide the update as soon as possible.
> 
> In the meantime, I kindly request that you don’t assign this issue to anyone else or merge any related pull requests.
> 
> Thank you for your understanding!

take your time
