### ISSUE TITLE
The current search bar is not good user experience and is not visible

### ISSUE THREAD

**Issue by PraveenUppar** [Mehtarishita/StationGuide#70]
# 🖥️ Frontend Issue

### **Description**
The current search bar is not a good user experience and it is not visible
### **Steps to Reproduce**

1. Navigate to the homepage.
2. Click on the search bar.
3. Observe the search bar's design and behaviour.

### **Expected behavior**

- A visually appealing and user-friendly search bar that complements the website's design.
- Smooth functionality, including responsive behaviour and clear, readable text.

### **Actual behavior**

- The search bar appears out of place.
- The design feels inconsistent and doesn't offer an goodexperience for users.

### **Screenshots or Video**

![Screenshot 2024-10-05 233515](https://github.com/user-attachments/assets/5c90bec4-acb5-40f6-a7c3-afdfca33e921)

### Are you participating in GSSoC?
- Yes

**Comment by dhairyagothi** [comment]
dont create multiple issues
