### ISSUE TITLE
Implementing a Dedicated 'Contact Us' Page for Improved User Support

### ISSUE THREAD

**Issue by rebornstar1** [Mehtarishita/StationGuide#75]
# ✨ Feature Request

### **Description of the Feature**
A "Contact Us" page for users to easily communicate with the platform’s support team. This feature will provide multiple channels for users to seek help, give feedback, or ask questions.

### **Problem Statement**
Currently, there is no dedicated page for users to reach out for support or assistance. This can make it difficult for users to report issues, ask questions, or seek guidance, which can negatively impact user experience.

### **Proposed Solution**
Implement a "Contact Us" page that includes:
- A form for submitting queries, including fields for name, email, and message.
- Contact information (email, phone, and mailing address).
- Links to social media profiles.
- An FAQ section for quick answers to common questions.

### **Additional Context**
Adding this page will improve user support and engagement, making the platform more accessible to all users, particularly those needing help or having questions about the system. Screenshots of the form and layout could be included during design review.

### **Are you participating in GSSoC?**
- [*] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
Hey @rebornstar1 

Can you share some detail what do you want to add in contact page .. 

This will be govt website so don't want like other websites
