### ISSUE TITLE
The Translate google is not looking good in the top, can try changing the position and size of the container

### ISSUE THREAD

**Issue by kanduru-abhiram** [Mehtarishita/StationGuide#77]
# 🖥️ Frontend Issue

### **Description**
This is a feature enhancement and frontend issue. The translate google api container doesn't look good which interrupts the other options in the left

### **Expected behavior**
May be rechange the position of google translate option

### **Actual behavior**
Translate google option is interrupting the other options and looks a bit of space occupied.

### **Screenshots or Video**
![image](https://github.com/user-attachments/assets/7d687891-bce6-46b2-b9ff-ac446cf42ec1)

### Are you participating in GSSoC?
- [ ] Yes
- [X] No

Kindly assign me this issue under Hacktoberfest 2024.

**Comment by iamsaura8h** [comment]
@dhairyagothi CAN YOU ASSIGN ME THIS ISSUE PLEASE !

**Comment by dhairyagothi** [comment]
Assigned @kanduru-abhiram

**Comment by dhairyagothi** [comment]
@iamsaura8h find some new issue

**Comment by kanduru-abhiram** [comment]
Please add hacktoberfest label too along with hacktober-accepted

![image](https://github.com/user-attachments/assets/6a9af76e-fd58-4b90-9c9a-576607584fd7)

**Comment by dhairyagothi** [comment]
> Please add hacktoberfest label too along with hacktober-accepted
> 
> ![image](https://private-user-images.githubusercontent.com/85011280/373948534-6a9af76e-fd58-4b90-9c9a-576607584fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjk0NDksIm5iZiI6MTcyODIyOTE0OSwicGF0aCI6Ii84NTAxMTI4MC8zNzM5NDg1MzQtNmE5YWY3NmUtZmQ1OC00YjkwLTljOWEtNTc2NjA3NTg0ZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE1MzkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMDQ0MThjZWFkMmVjZWQ2ZjBiODhmNDhlNDAyMDc2ZjhhOGRhNThhYjdmNDZkYzdhYjUwZTkzZmRjMjQ4OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._p-fHZWLWu3X5vk-FM-3NcqYdb2_PZx4X6HAzGOzEpg)

already added let me check PR
