### ISSUE TITLE
Google "Select Language" Dropdown Image Misplaced or Overlaying UI

### ISSUE THREAD

**Issue by GitWizzz** [Mehtarishita/StationGuide#78]
# 🖥️ Frontend Issue

### **Description**
The Google "Select Language" dropdown is misplaced and overlays other UI elements at the top of the page. This impacts user interaction and overall design consistency.

### **Steps to Reproduce**

1. Go to the affected page (provide the URL or specific page name).
2. Locate the "Select Language" dropdown at the top.
3. Observe that the dropdown image is overlapping with other content on the page.

### **Expected behavior**
The Google "Select Language" dropdown should be positioned properly without interfering with other elements on the page.

### **Actual behavior**
The dropdown image appears to float at the top and overlaps critical UI elements, affecting navigation and visibility.

### **Screenshots or Video**
![4](https://github.com/user-attachments/assets/c83e9c62-74b0-4133-b35c-4247bf878298)

### Are you participating in GSSoC?
Yes

**Comment by dhairyagothi** [comment]
Okay fix it @GitWizzz

**Comment by 29akeshvimt** [comment]
may you assign this issue to me

**Comment by dhairyagothi** [comment]
> may you assign this issue to me

go ahead @29akeshvimt
