### ISSUE TITLE
Fixing Station Saarthi logo SVG 

### ISSUE THREAD

**Issue by dhairyagothi** [Mehtarishita/StationGuide#8]
# ✨ Feature Request

Fixing blury SVG on herosection 

### **Problem Statement**

![image](https://github.com/user-attachments/assets/888f9e1c-3355-407a-a72e-f57b903574de)

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by Mehtarishita** [comment]
Please assign this issue to me.

**Comment by dhairyagothi** [comment]
> Please assign this issue to me.

Lessss gooo @Mehtarishita  
Assigned

**Comment by dhairyagothi** [comment]
@all-contributors please add @dhairyagothi  for code

**Comment by anushkaa-dubey** [comment]
I would like to work on fixing the blurry SVG in the hero section for GSSOC'24 extended and Hacktoberfest. Here's my plan:

Problem: The SVG in the hero section looks blurry.
Solution: I'll make sure the SVG is properly scaled for different screen sizes, adjust the viewBox if needed, and try increasing its resolution to improve clarity. I’ll also check for any CSS issues that might affect its appearance.
I’m excited to contribute and look forward to your guidance on this!

**Comment by dhairyagothi** [comment]
> I would like to work on fixing the blurry SVG in the hero section for GSSOC'24 extended and Hacktoberfest. Here's my plan:
> 
> Problem: The SVG in the hero section looks blurry. Solution: I'll make sure the SVG is properly scaled for different screen sizes, adjust the viewBox if needed, and try increasing its resolution to improve clarity. I’ll also check for any CSS issues that might affect its appearance. I’m excited to contribute and look forward to your guidance on this!

Sure @anushkaa-dubey  assigning you this please update me with changes or any help if needed good luck

**Comment by Yashhuc** [comment]
Hey, I would like to work on this issue. Do we have to create a new SVG-log (a clear one), or do we have to make changes in this logo only, so that it is clearly visible, or just adjust the CSS to the img tag to handle it on different screens? If we have to implement the last feature, then I have done it already. 
Please let me know and assign this issue to me.

**Comment by dhairyagothi** [comment]
Wait @Yashhuc

**Comment by dhairyagothi** [comment]
@Mehtarishita @anushkaa-dubey pls update with your work . If you have any query you can ask

**Comment by anushkaa-dubey** [comment]
Working on it, should i send a clearer version of the svg or have to do it with css?

**Comment by dhairyagothi** [comment]
> Working on it, should i send a clearer version of the svg or have to do it with css?

@anushkaa-dubey i think svg is blur .... you have to change svg only.....

should i share clear images ??
