### ISSUE TITLE
# Elevate User Experience by Introducing a Custom Cursor and increasing responsiveness 

### ISSUE THREAD

**Issue by AnujShrivastava01** [Mehtarishita/StationGuide#80]
# Description:

I propose adding a custom cursor to the website to enhance the overall user experience. A visually appealing and unique cursor design can significantly increase engagement by giving the site a more polished and modern feel, differentiating it from competitors.
Also I will work on the responsiveness of website .
# Benefits:
Improved User Experience
Brand Identity Enhancement
Increased Interaction

Assign this to me .
Thankyou !

**Comment by dhairyagothi** [comment]
Nice please add @AnujShrivastava01

**Comment by Sourabh782** [comment]
Hello @dhairyagothi, i see this issue is unresolved from past 2 weeks, if its avaible for reallocation, i am intrested in completing this issue

**Comment by dhairyagothi** [comment]
custom cursor is already there @Sourabh782
