### ISSUE TITLE
Feat : New Global Font Style to Entire Webpage

### ISSUE THREAD

**Issue by iamsaura8h** [Mehtarishita/StationGuide#81]
# ✨ Feature Request

### **Description of the Feature**
I would like to propose the addition of a new font style that will be applied across the entire webpage to enhance the overall aesthetics and readability. This feature will ensure a unified look and feel for all text elements on the site.

### **Problem Statement**
Currently, the page uses the default or inconsistent font styles in various sections, which impacts the visual appeal and readability of the content. A consistent and appealing font style can help establish a stronger brand identity and improve the user experience.

### **Proposed Solution**
Introduce a modern, visually pleasing font like "Poppins" or "Roboto" for Entire Page

### **Alternatives Considered**

-Use a custom font through web hosting.
-Maintain the current fonts but ensure consistency by standardizing the existing ones.

### **Additional Context**
Implementing a global font change can drastically improve the website's UI/UX and appeal. Below is a reference screenshot of the new font:

![image](https://github.com/user-attachments/assets/365ad6a0-3f85-44d2-a39c-82ef7b6cc4e2)

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

### Please Assign me this issue with `gssoc-ext` and `hacktoberfest-accepted` labels so i can start working on it right away

**Comment by dhairyagothi** [comment]
@iamsaura8h do it but share me ss before making PR

**Comment by iamsaura8h** [comment]
Okay @dhairyagothi , 
by using this font , the font looks smooth and better than the default one , has good pixel density so it doesn't shred down if we zoom a bit more plus it looks better.
I have also adjusted the size of "Namaste Yatree" with some padding-top and for "Station Sarthi : Your Platform Guide" heading too. Now it looks more distinguished.
here's a preview for poppins font :
### new home page
<img width="960" alt="is11 1" src="https://github.com/user-attachments/assets/1f92ceab-1866-448e-9c5c-2d1217a37d40">

<hr>

### login page 
before : 
<img width="250" alt="is11 2" src="https://github.com/user-attachments/assets/197c99f4-54bb-4d00-bc32-0cef92b78d31">

after : 
<img width="258" alt="is11LoginSol" src="https://github.com/user-attachments/assets/507470c8-7a27-48b9-9f05-6f103be197f3">

Signal me if you find this useful so that i can create a PR for this .

**Comment by dhairyagothi** [comment]
@iamsaura8h let me check font in figma design then I will tell

**Comment by iamsaura8h** [comment]
> @iamsaura8h let me check font in figma design then I will tell

@dhairyagothi all set ?

**Comment by dhairyagothi** [comment]
yes go for it @iamsaura8h

**Comment by iamsaura8h** [comment]
yeah i just changed the font globally for this app and increased font weight and size for heading and subheading.
going to raise a PR for this momentarily.
It works as just shown in above screenshots.

Thank you
