### ISSUE TITLE
Changing Hamburger menu as Figma UI

### ISSUE THREAD

**Issue by RiddhiM170904** [Mehtarishita/StationGuide#82]
# 🖥️ Frontend Issue

### **Description**

I will make complete Hamburger as Figma UI

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### Are you participating in GSSoC?
 Yes

Please assign me this under GSSoc'24 Extd and HACKTOBERFEST.

**Comment by dhairyagothi** [comment]
Yess Riddhi go for it make sure to don't change UI and add all options in Hamburger . Design complete Hamburger @RiddhiM170904

**Comment by srishti023** [comment]
Please assign me this issue
