### ISSUE TITLE
Fixing Search bar's look 

### ISSUE THREAD

**Issue by iamsaura8h** [Mehtarishita/StationGuide#83]
hey @dhairyagothi ,

## Description 
the search bar when expanded has unnecessary border color which affects the ui ux . 
so i want to solve this issue by removing the border color.

## Screenshot 
<img width="230" alt="{AFB5C16A-8D0E-4B29-9B21-7124A4CB6EDC}" src="https://github.com/user-attachments/assets/aeab904b-3d5b-4c86-ac45-9667eeaad64c">

### Please assign me this issue with `gssoc-ext` and `hacktoberfest-accepted` so i can start working on it right away.

**Comment by PraveenUppar** [comment]
I have already raised the issue regarding this earlier once check with it and let me know @dhairyagothi 
Issue #70 
PR #71
