### ISSUE TITLE
Register link not working on Login page

### ISSUE THREAD

**Issue by iamsaura8h** [Mehtarishita/StationGuide#84]
# 🐞 Bug Report

### **Describe the bug**
The register link as "Don't have an account? [Register](https://stationguide.onrender.com/Register)" on Login Route isn't working and showing Not found when clicked on it.

### **Steps to Reproduce**
Steps to reproduce the behavior:1. Go to '...'
1. Click on 'Login'
2. Scroll down to 'Don't have an account? Register'
3. See error

### **Expected behavior**
User should be redirected to Register route

### **Actual behavior**
Throws error as Not found

### **Screenshots or Video**
<img width="356" alt="is9 1" src="https://github.com/user-attachments/assets/cd0b2cfd-d448-462d-a66d-725060ce6cd3">
<br>
<img width="356" alt="is2" src="https://github.com/user-attachments/assets/406229b2-e7d9-4339-8953-b5187ab65271">

### **Logs & Error Messages**
"Not Found"

<hr>

**Comment by dhairyagothi** [comment]
I got it @iamsaura8h it's just one word change i will not be able to assign you any level for it .. 
And it's problem while hosting.
