### ISSUE TITLE
Changing complete ui of chatbot and personalized questions 

### ISSUE THREAD

**Issue by Mehtarishita** [Mehtarishita/StationGuide#85]
# 🖥️ Frontend Issue

### **Description**

2. Click on '...'
3. See error '...'

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
@Mehtarishita please add proper discription always

**Comment by dhairyagothi** [comment]
Change UI of chatbot as Figma design and ask me questions before adding . 

@Mehtarishita assigned 

Will change level after PR

**Comment by HimangshuSharma01** [comment]
assign me i can do this
