### ISSUE TITLE
Making Hamburger function Properly 

### ISSUE THREAD

**Issue by dhairyagothi** [Mehtarishita/StationGuide#9]
# ✨ Feature Request

### **Description of the Feature**

Making Hamburger function Properly 

![image](https://github.com/user-attachments/assets/087558c9-5ec8-4c70-86dd-6bf50eb9ffd3)

fixing top and bottom 

### **Alternatives Considered**

Points will be assigned according to PR content 

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

**Comment by 1-SubhamSingh** [comment]
Hey there,
I am interested in working on this task , can you please assign me this task.

**Comment by c2gup** [comment]
Hi @dhairyagothi,

I hope you’re doing well! I’m interested in working on the issue regarding the hamburger menu functionality (). I believe I can help with fixing the top and bottom alignment as well as ensuring the menu functions properly.

Could you please assign this task to me? I’m eager to contribute!

Thank you!

Best,
Anupam Gupta

**Comment by dhairyagothi** [comment]
Assigned @1-SubhamSingh  please make sure to read all readme files and make same UI given in  '''stationguidefigma.md''' 
And while creating PR don't change template and add screenshot of work 

Go ahead .... 
Please update me in 24 hours with status of your work otherwise i have to assign it to other as we have very few days to contribute ...

**Comment by dhairyagothi** [comment]
@c2gup thanku for showing interest in repository. This is issue is assigned . 

It's rule and a best practice of open source to assign issues on first come basis 

If no work is done in 24 hours then i will assign you. 

Find some different issue and create a new issue . 

I will assign you .

**Comment by dhairyagothi** [comment]
?? Updates @1-SubhamSingh

**Comment by 1-SubhamSingh** [comment]
Working on it , I'll  update you finally by today itself

**Comment by dhairyagothi** [comment]
> Working on it , I'll update you finally by today itself

okkk

**Comment by 1-SubhamSingh** [comment]
@dhairyagothi Did some changes you can check and merge my first open source contribution :)

**Comment by dhairyagothi** [comment]
> @dhairyagothi Did some changes you can check and merge my first open source contribution :)
>  

That's great just check PR
