### ISSUE TITLE
ReadMe file missing commands

### ISSUE THREAD

**Issue by PraveenUppar** [Mehtarishita/StationGuide#92]
Missing Install dependencies for both the backend and frontend:

Install backend dependencies:

cd backend
npm install
npm run start

Install frontend dependencies:

cd ../frontend
npm install
npm run dev

![Screenshot 2024-10-06 192910](https://github.com/user-attachments/assets/6c61984a-3529-44b9-984e-ee500166f093)

**Comment by PraveenUppar** [comment]
Once check with the issue and assign me I will resolve the issue 
If yes then add labels of gssoc-ext and hacktoberfest-accepted

**Comment by dhairyagothi** [comment]
already enough content in readme file bro
