### ISSUE TITLE
Readme.md updation

### ISSUE THREAD

**Issue by eshalshaikh07** [Mehtarishita/StationGuide#93]
Hi Team,

I’ve been going through the project and am impressed with what’s been accomplished so far. To attract audience and make it engaging I want to further improve the user experience, I’d like to propose some changes to the README.md file, including adding animations or icons, reorganizing text alignment, and introducing a few more subtle tweaks to make the content more engaging and easy to follow.

I believe these updates can make the documentation more visually appealing and improve clarity for new contributors. I’d be excited to help implement these changes and ensure the README effectively represents the quality of this project.

Looking forward to your thoughts!

**Comment by eshalshaikh07** [comment]
I would like to work on it.

**Comment by dhairyagothi** [comment]
its already enough content in readme file  bro 
sorry but closing issue
