### ISSUE TITLE
UI Landing Page Should not be moving and should be fixed.

### ISSUE THREAD

**Issue by Raja-Abrar-Khan** [Mehtarishita/StationGuide#94]
# 🖥️ Frontend Issue

### **Description**
When you go to the website you see the Height of the website is not aligning with the page. Page should not move up or down with cursor it should be fixed and because of this the ui is also suffering . I will Paste the ScreenShot down to let you see How bad the Ui is looking and because of wrong height the text color is also overlapping.

![Screenshot 2024-10-06 204130](https://github.com/user-attachments/assets/989bd038-ff68-4835-adcf-609c75112ebd)
![Screenshot 2024-10-06 204151](https://github.com/user-attachments/assets/e55b8a4d-864e-4a95-8a22-53c859597b86)

### Are you participating in GSSoC?
 Yes

**Comment by Raja-Abrar-Khan** [comment]
@dhairyagothi  Assign this issue to me

**Comment by dhairyagothi** [comment]
bro fixing will hide many of content in different screen size
