### ISSUE TITLE
When Go to login , the text is not visible

### ISSUE THREAD

**Issue by Raja-Abrar-Khan** [Mehtarishita/StationGuide#95]
# 🖥️ Frontend Issue

### **Description**
When you click on the login page the text is not visible and it can be lot better than as it is Now.

### **Screenshots or Video**
![Screenshot 2024-10-06 205641](https://github.com/user-attachments/assets/dc929b92-cf16-44f0-b928-c3dfbb2b2ee9)

![Screenshot 2024-10-06 205647](https://github.com/user-attachments/assets/21b149f4-dd10-4c3e-ad31-7c6422ba79e0)

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

**Comment by Raja-Abrar-Khan** [comment]
@dhairyagothi  Assign This issue to me

**Comment by dhairyagothi** [comment]
there is alreay same issue for that alignment
assigning you if can make some else changes . lets see

**Comment by Raja-Abrar-Khan** [comment]
@dhairyagothi  I will start work on this .
