### ISSUE TITLE
alignment of herosection    

### ISSUE THREAD

**Issue by RiddhiM170904** [Mehtarishita/StationGuide#96]
# 🖥️ Frontend Issue

### **Description**
Herosection alignment is changed by chatbot and language icon i will fix it please assign me this issue under gssoc'24 extd and hacktoberfest.

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### Are you participating in GSSoC?
Yes

**Comment by dhairyagothi** [comment]
please make PR fast @RiddhiM170904
