### ISSUE TITLE
[Bug] 🐞 Correct Background Image Placement on Website

### ISSUE THREAD

**Issue by iarmaanx** [Mehtarishita/StationGuide#97]
The current background image on the website is not displaying correctly, leading to alignment and scaling issues. This affects the visual appeal and responsiveness of the page, especially on different screen sizes.

Steps to Reproduce
Go to the homepage.
Resize the browser window or view the page on a mobile device.
Notice the background image misalignment or distortion.
Expected Behavior
The background image should:

Be correctly centered and aligned.
Scale proportionally without being stretched or cropped.
Adapt seamlessly across all screen sizes (mobile, tablet, desktop).
Actual Behavior
The background image appears misaligned or stretched on certain screen sizes.
The image does not scale correctly on mobile devices, causing distortion.

![Screenshot 2024-10-06 221037](https://github.com/user-attachments/assets/ee9bac20-31be-4201-8744-26e124135e8a)

### Are you participating in GSSoC?
- [+] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
there is a same issue bro #96 let it be resolved

**Comment by iarmaanx** [comment]
Git it dude 🤗
