### ISSUE TITLE
Adding routes in herosection icons

### ISSUE THREAD

**Issue by Kajalmehta29** [Mehtarishita/StationGuide#98]
# ✨ Feature Request

### **Description of the Feature**

I will add routes in herosection icons website.

Please assign this issue to me under gssoc and hacktoberfest.

### **Are you participating in GSSoC?**
- [ +] Yes
- [ ] No

**Comment by dhairyagothi** [comment]
@Kajalmehta29  please update all routes properly 
use `React-Dom`  go ahead 
happy contributing......
