### ISSUE TITLE
UI is not user friendly

### ISSUE THREAD

**Issue by AkshatBari02** [Mehtarishita/StationGuide#99]
# 🖥️ Frontend Issue

### **Description**
Two Chatbot icons on the home page: 
One on the top left corner and another at the bottom right corner making users confused which one is correctly working.

Unnecessary option of translating the website content into different languages using google translator as there is already an available feature of converting website content into different languages in browser
Still if required it should be adjusted in some proper manner that does not make the page look bad.

Wrong colors are used for text:
White color on white background
Black color on dark part of background 

There should be only one background image

### **Steps to Reproduce**

2. Click on '...'
3. See error '...'

### **Expected behavior**
Only one chatbot button should be there
If required a translating content option then it should be in the navigation bar or in this case in the hamburger options.
Dark color and light color should be used on light and dark backgrounds respectively for text
only one background image should be there.

### **Actual behavior**
Two chatbot icons 
wrong use of colors
translating option is displayed in wrong manner making bad user experience

### **Screenshots or Video**
<!-- If applicable, add screenshots or video to help explain your issue. --
![Capture - 3](https://github.com/user-attachments/assets/503f75a5-c517-4183-886e-a2acfc2cc7a2)
![Capture-2](https://github.com/user-attachments/assets/1bab36fd-67dd-45ae-a1a6-050fa217de17)
>

### Are you participating in GSSoC?
- [+] Yes
- [ ] No

Please assign this issue to me under gssoc-ext and hacktoberfest

**Comment by dhairyagothi** [comment]
yaa bro check current PR merged i think your issue is resolved if anything else let me know

**Comment by AkshatBari02** [comment]
@dhairyagothi 

Only two icons for Chatbot has been solved but rest of the issues are same
Translating content option is not looking good on the page 
color combinations on the page are not good

![image](https://github.com/user-attachments/assets/fb91c6b8-ce94-4a76-8d02-a821ba36f558)
image of the page available on render

**Comment by dhairyagothi** [comment]
dont change figma design UI 
first check Stationguidefigma.md
